Repository MCLD/greatreadingadventure, pull requests merged in 2018-12, with the labels that each got.

#381 Fix development version number to 4.1.1
  CHANGELOG.md
  appveyor.yml
  src/GRA.CommandLine/GRA.CommandLine.csproj
  src/GRA.Controllers/GRA.Controllers.csproj
  src/GRA.Data.SQLite/GRA.Data.SQLite.csproj
  src/GRA.Data.SqlServer/GRA.Data.SqlServer.csproj
  src/GRA.Data/GRA.Data.csproj
  src/GRA.Domain.Model/GRA.Domain.Model.csproj
  src/GRA.Domain.Report/GRA.Domain.Report.csproj
  src/GRA.Domain.Repository/GRA.Domain.Repository.csproj
  src/GRA.Domain.Service/GRA.Domain.Service.csproj
  src/GRA.Security/GRA.Security.csproj
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/web.config
  src/GRA/GRA.csproj
Labels: developer

#378 Fix error with adding challenge tasks
  CHANGELOG.md
  src/GRA.Data/Repository/ChallengeTaskRepository.cs
Labels: bug

#384 Fix Docker latest image build to include avatars
  docker-build.bash
Labels: developer

#386 Fix viewing challenge groups
  CHANGELOG.md
  src/GRA.Data/Profile/MappingProfile.cs
Labels: bug

#387 Fix stacked Font Awesome mail/gift icons
  CHANGELOG.md
  src/GRA.Web/Areas/MissionControl/Views/Participants/Household.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Shared/_Layout.cshtml
  src/GRA.Web/Views/Home/IndexAccessClosed.cshtml
  src/GRA.Web/Views/Home/IndexBeforeRegistration.cshtml
  src/GRA.Web/Views/Profile/Household.cshtml
  src/GRA.Web/Views/Shared/_Layout.cshtml
Labels: .NET Core 2, bug

#388 Fix household group button showing
  CHANGELOG.md
  src/GRA.Controllers/MissionControl/ParticipantsController.cs
  src/GRA.Controllers/ViewModel/MissionControl/Participants/HouseholdListViewModel.cs
  src/GRA.Web/Areas/MissionControl/Views/Participants/Household.cshtml
Labels: bug

#390 Add test for distributed cache configuration
  src/GRA.Web/Web.cs
Labels: developer, enhancement

#392 Incorporate fixes for 4.1.1
  CHANGELOG.md
  docs/technical/appsettings.md
  src/GRA.Controllers/MissionControl/GroupTypesController.cs
  src/GRA.Controllers/ViewModel/MissionControl/GroupTypes/GroupTypesListViewModel.cs
  src/GRA.Data/AuditingRepository.cs
  src/GRA.Data/Model/AvatarLayer.cs
  src/GRA.Data/Repository/AvatarBundleRepository.cs
  src/GRA.Data/Repository/BadgeRepository.cs
  src/GRA.Data/Repository/BranchRepository.cs
  src/GRA.Data/Repository/CategoryRepository.cs
  src/GRA.Data/Repository/ChallengeGroupRepository.cs
  src/GRA.Data/Repository/ChallengeRepository.cs
  src/GRA.Data/Repository/DailyLiteracyTipRepository.cs
  src/GRA.Data/Repository/DrawingCriterionRepository.cs
  src/GRA.Data/Repository/DrawingRepository.cs
  src/GRA.Data/Repository/GroupInfoRepository.cs
  src/GRA.Data/Repository/LocationRepository.cs
  src/GRA.Data/Repository/MailRepository.cs
  src/GRA.Data/Repository/QuestionnaireRepository.cs
  src/GRA.Data/Repository/TriggerRepository.cs
  src/GRA.Data/Repository/UserRepository.cs
  src/GRA.Data/Repository/VendorCodeTypeRepository.cs
  src/GRA.Web/Areas/MissionControl/Views/GroupTypes/Index.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Sites/Settings.cshtml
  src/GRA.Web/Startup.cs
  src/GRA.Web/Views/Challenges/Index.cshtml
  src/GRA.Web/wwwroot/css/gra.css
  src/GRA.Web/wwwroot/css/main.min.css
  src/GRA/ConfigurationKey.cs
Labels: bug, documentation, enhancement

#393 Add and update site customization
  .gitignore
  CHANGELOG.md
  GRARuleSet.ruleset
  GreatReadingAdventure.sln
  docs/index.rst
  docs/installation/configuration.md
  docs/installation/upgrading.md
  docs/setup/adding-avatars.md
  docs/setup/site-customizations.md
  docs/technical/appsettings.md
  src/GRA.CommandLine/GRA.CommandLine.csproj
  src/GRA.Controllers/Base/Controller.cs
  src/GRA.Controllers/Filter/SessionTimeoutFilter.cs
  src/GRA.Controllers/Filter/SiteFilter.cs
  src/GRA.Controllers/GRA.Controllers.csproj
  src/GRA.Controllers/ItemKey.cs
  src/GRA.Data.SQLite/GRA.Data.SQLite.csproj
  src/GRA.Data.SqlServer/GRA.Data.SqlServer.csproj
  src/GRA.Data/GRA.Data.csproj
  src/GRA.Domain.Model/GRA.Domain.Model.csproj
  src/GRA.Domain.Report/GRA.Domain.Report.csproj
  src/GRA.Domain.Repository/GRA.Domain.Repository.csproj
  src/GRA.Domain.Service/GRA.Domain.Service.csproj
  src/GRA.Domain.Service/SiteLookupService.cs
  src/GRA.Domain.Service/TemplateService.cs
  src/GRA.Domain.Service/TriggerService.cs
  src/GRA.Security/GRA.Security.csproj
  src/GRA.Web/Areas/MissionControl/Views/Home/AuthorizationCode.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Shared/_Layout.cshtml
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/Startup.cs
  src/GRA.Web/Views/Shared/_Layout.cshtml
  src/GRA.Web/wwwroot/css/gra.css
  src/GRA.Web/wwwroot/css/main.min.css
  src/GRA.Web/wwwroot/css/site.css
  src/GRA.Web/wwwroot/fonts/FontAwesome.otf
  src/GRA.Web/wwwroot/fonts/fontawesome-webfont.eot
  src/GRA.Web/wwwroot/fonts/fontawesome-webfont.svg
  src/GRA.Web/wwwroot/fonts/fontawesome-webfont.ttf
  src/GRA.Web/wwwroot/fonts/fontawesome-webfont.woff
  src/GRA.Web/wwwroot/fonts/fontawesome-webfont.woff2
  src/GRA/CacheKey.cs
  src/GRA/ClaimType.cs
  src/GRA/GRA.csproj
  src/GRA/SiteSettingDefinitions.cs
  src/GRA/SiteSettingKey.cs
Labels: bug, enhancement

#394 Update project for ASP.NET Core 2.2
  CHANGELOG.md
  Dockerfile
  dev/Dockerfile
  src/GRA.CommandLine/GRA.CommandLine.csproj
  src/GRA.Controllers/GRA.Controllers.csproj
  src/GRA.Data.SQLite/GRA.Data.SQLite.csproj
  src/GRA.Data.SqlServer/GRA.Data.SqlServer.csproj
  src/GRA.Data/GRA.Data.csproj
  src/GRA.Domain.Model/GRA.Domain.Model.csproj
  src/GRA.Domain.Report/GRA.Domain.Report.csproj
  src/GRA.Domain.Service/GRA.Domain.Service.csproj
  src/GRA.Security/GRA.Security.csproj
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/Startup.cs
  src/GRA.Web/web.config
  src/GRA/GRA.csproj
Labels: developer, enhancement

#398 Fix development version number to 4.1.2-beta
  CHANGELOG.md
  appveyor.yml
  docker-build.bash
  src/GRA.CommandLine/GRA.CommandLine.csproj
  src/GRA.Controllers/GRA.Controllers.csproj
  src/GRA.Data.SQLite/GRA.Data.SQLite.csproj
  src/GRA.Data.SqlServer/GRA.Data.SqlServer.csproj
  src/GRA.Data/GRA.Data.csproj
  src/GRA.Domain.Model/GRA.Domain.Model.csproj
  src/GRA.Domain.Report/GRA.Domain.Report.csproj
  src/GRA.Domain.Repository/GRA.Domain.Repository.csproj
  src/GRA.Domain.Service/GRA.Domain.Service.csproj
  src/GRA.Security/GRA.Security.csproj
  src/GRA.Web/GRA.Web.csproj
  src/GRA/GRA.csproj
Labels: developer

#399 Fix logging, update analytics
  CHANGELOG.md
  src/GRA.Controllers/Filter/UserFilter.cs
  src/GRA.Controllers/HomeController.cs
  src/GRA.Controllers/ItemKey.cs
  src/GRA.Controllers/SignInController.cs
  src/GRA.Controllers/TempDataKey.cs
  src/GRA.Controllers/ViewModel/Home/DashboardViewModel.cs
  src/GRA.Web/LogConfig.cs
  src/GRA.Web/Program.cs
  src/GRA.Web/Views/Home/Dashboard.cshtml
  src/GRA.Web/Views/Shared/_Layout.cshtml
Labels: developer, enhancement
