Repository MCLD/greatreadingadventure, pull requests merged in 2018-05, with the labels that each got.

#292 Add {Link} token to vendor code mails
  CHANGELOG.md
  src/GRA.Domain.Service/VendorCodeService.cs
  src/GRA/TemplateToken.cs
Labels: enhancement

#293 Disable Visual Studio TypeScript compilation
  .gitignore
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/wwwroot/lib/bootstrap-multiselect/types/bootstrap-multiselect/tsconfig.json
Labels: developer

#295 Improve site management and startup logging
  src/GRA.Controllers/JoinController.cs
  src/GRA.Controllers/ViewModel/Join/AuthorizationCodeViewModel.cs
  src/GRA.Controllers/ViewModel/MissionControl/Sites/SiteConfigurationViewModel.cs
  src/GRA.Controllers/ViewModel/MissionControl/Sites/SiteSocialMediaViewModel.cs
  src/GRA.Data.SQLite/SQLiteContext.cs
  src/GRA.Data.SqlServer/SqlServerContext.cs
  src/GRA.Data/Context.cs
  src/GRA.Data/Model/Site.cs
  src/GRA.Domain.Model/Site.cs
  src/GRA.Web/Areas/MissionControl/Views/Sites/Configuration.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Sites/SocialMedia.cshtml
  src/GRA.Web/Startup.cs
  src/GRA.Web/Views/Join/AuthorizationCode.cshtml
Labels: developer, enhancement

#297 Fix missing site logo url on authcode post
  src/GRA.Controllers/JoinController.cs
Labels: bug

#298 Add bundling of CSS and JavaScript assets
  src/GRA.Web/Areas/MissionControl/Views/Challenges/Edit.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Dashboard/Detail.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Home/AuthorizationCode.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Pages/Create.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Pages/Edit.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Shared/_Layout.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Sites/Detail.cshtml
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/Views/Avatar/Index.cshtml
  src/GRA.Web/Views/Shared/_Layout.cshtml
  src/GRA.Web/bundleconfig.json
  src/GRA.Web/wwwroot/css/gra.min.css
  src/GRA.Web/wwwroot/css/main.min.css
  src/GRA.Web/wwwroot/css/markdown.min.css
  src/GRA.Web/wwwroot/css/slick.min.css
  src/GRA.Web/wwwroot/fonts/FontAwesome.otf
  src/GRA.Web/wwwroot/fonts/fontawesome-webfont.eot
  src/GRA.Web/wwwroot/fonts/fontawesome-webfont.svg
  src/GRA.Web/wwwroot/fonts/fontawesome-webfont.ttf
  src/GRA.Web/wwwroot/fonts/fontawesome-webfont.woff
  src/GRA.Web/wwwroot/fonts/fontawesome-webfont.woff2
  src/GRA.Web/wwwroot/js/WMD.min.js
  src/GRA.Web/wwwroot/js/gra.min.js
  src/GRA.Web/wwwroot/js/main.min.js
  src/GRA.Web/wwwroot/js/markdown.min.js
Labels: enhancement

#300 Add missing files, log HTTP errors, modify build
  src/GRA.Controllers/ErrorController.cs
  src/GRA.Controllers/UserContextProvider.cs
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/Startup.cs
  src/GRA.Web/appsettings.json
  src/GRA.Web/wwwroot/css/ajax-loader.gif
  src/GRA.Web/wwwroot/fonts/slick.eot
  src/GRA.Web/wwwroot/fonts/slick.svg
  src/GRA.Web/wwwroot/fonts/slick.ttf
  src/GRA.Web/wwwroot/fonts/slick.woff
  src/GRA/ConfigurationKey.cs
Labels: bug, developer, enhancement

#301 Improve school district selection
  CHANGELOG.md
  src/GRA.Controllers/JoinController.cs
  src/GRA.Controllers/MissionControl/ParticipantsController.cs
  src/GRA.Controllers/ProfileController.cs
Labels: enhancement

#302 Improve avatar share pages, modify builds
  .travis.yml
  CHANGELOG.md
  appveyor.yml
  src/GRA.Controllers/Helpers/SiteTagHelper.cs
  src/GRA.Web/Views/Avatar/Share.cshtml
  src/GRA.Web/Views/Share/Avatar.cshtml
  src/GRA.Web/wwwroot/css/gra.css
  src/GRA.Web/wwwroot/css/main.min.css
Labels: enhancement

#303 Move slick fonts to correct location
  src/GRA.Web/wwwroot/css/fonts/slick.eot
  src/GRA.Web/wwwroot/css/fonts/slick.svg
  src/GRA.Web/wwwroot/css/fonts/slick.ttf
  src/GRA.Web/wwwroot/css/fonts/slick.woff
Labels: bug

#304 Fix permission for listing vendor code types
  CHANGELOG.md
  src/GRA.Domain.Service/VendorCodeService.cs
Labels: bug

#310 Fix deleting challenge groups
  CHANGELOG.md
  src/GRA.Web/Areas/MissionControl/Views/Challenges/Groups.cshtml
Labels: bug

#314 Fix title of page for community experiences
  CHANGELOG.md
  src/GRA.Controllers/MissionControl/EventsController.cs
Labels: bug

#315 Fix title of public page for community experiences
  src/GRA.Controllers/EventsController.cs
Labels: enhancement

#319 Improve reporting
  CHANGELOG.md
  src/GRA.Controllers/MissionControl/ReportingController.cs
  src/GRA.Controllers/ViewModel/MissionControl/Reporting/ReportCriteriaViewModel.cs
  src/GRA.Controllers/ViewModel/MissionControl/Reporting/ReportResultsViewModel.cs
  src/GRA.Domain.Report/RegistrationsAchieversBySchoolReport.cs
  src/GRA.Domain.Service/SchoolService.cs
  src/GRA.Domain.Service/SiteService.cs
  src/GRA.Domain.Service/UserService.cs
  src/GRA.Web/Areas/MissionControl/Views/Reporting/ActivityByProgramCriteria.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Reporting/BadgeCriteria.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Reporting/BadgeTopScoresCriteria.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Reporting/CurrentStatusByProgramCriteria.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Reporting/ParticipantProgressCriteria.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Reporting/RegistrationsAndAchieversCriteria.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Reporting/View.cshtml
Labels: enhancement

#323 Add event location display improvements
  CHANGELOG.md
  src/GRA.Data/Repository/LocationRepository.cs
  src/GRA.Domain.Model/Location.cs
  src/GRA.Web/Areas/MissionControl/Views/Events/Locations.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Shared/_Layout.cshtml
Labels: bug

#325 Update Docker source images to microsoft/dotnet
  Dockerfile
  dev/Dockerfile
Labels: developer, enhancement

#327 Improve Travis build
  .travis.yml
  Dockerfile
  dev/Dockerfile
Labels: developer, enhancement

#329 Add Docker build script, push to Docker Hub
  .gitignore
  .travis.yml
  CHANGELOG.md
  dev/bin/docker-build.sh
Labels: developer, enhancement
