Repository MCLD/greatreadingadventure, pull requests merged in 2018-04, with the labels that each got.

#265 Add group improvements and fixes
  CHANGELOG.md
  src/GRA.Controllers/MissionControl/ParticipantsController.cs
  src/GRA.Controllers/MissionControl/ReportingController.cs
  src/GRA.Controllers/ProfileController.cs
  src/GRA.Controllers/ViewModel/MissionControl/Reporting/ReportCriteriaViewModel.cs
  src/GRA.Data/Model/ReportCriterion.cs
  src/GRA.Data/Repository/GroupInfoRepository.cs
  src/GRA.Domain.Model/ReportCriterion.cs
  src/GRA.Domain.Report/GroupVendorCodeReport.cs
  src/GRA.Domain.Repository/IGroupInfoRepository.cs
  src/GRA.Domain.Service/Abstract/BaseUserService.cs
  src/GRA.Domain.Service/UserService.cs
  src/GRA.Web/Areas/MissionControl/Views/Participants/Household.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Reporting/GroupVendorCodeCriteria.cshtml
  src/GRA.Web/Startup.cs
  src/GRA.Web/Views/Profile/GroupUpgrade.cshtml
Labels: bug, enhancement

#266 Add point translation management
  CHANGELOG.md
  src/GRA.Controllers/MissionControl/ProgramsController.cs
  src/GRA.Controllers/ViewModel/MissionControl/Programs/PointTranslationDetailViewModel.cs
  src/GRA.Controllers/ViewModel/MissionControl/Programs/PointTranslationsListViewModel.cs
  src/GRA.Data/Repository/UserLogRepository.cs
  src/GRA.Domain.Model/PointTranslation.cs
  src/GRA.Domain.Repository/IUserLogRepository.cs
  src/GRA.Domain.Service/PointTranslationService.cs
  src/GRA.Web/Areas/MissionControl/Views/Programs/Index.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Programs/PointTranslationDetail.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Programs/PointTranslations.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Programs/_ProgramsPartial.cshtml
Labels: enhancement

#269 Fix default avatar button not disabling on click
  CHANGELOG.md
  src/GRA.Web/Areas/MissionControl/Views/Avatars/Index.cshtml
Labels: bug

#272 Update manual for version 4
  CHANGELOG.md
  db/SQL-Server-createdb.sql
  docs/.gitignore
  docs/Makefile
  docs/conf.py
  docs/index.rst
  docs/installation/configuration.md
  docs/installation/create-the-database.md
  docs/installation/install-the-software-windows.md
  docs/installation/requirements-checklist.md
  docs/installation/system-requirements.md
  docs/introduction/overview.md
  docs/introduction/planning.md
  docs/make.bat
  docs/setup/adding-avatars.md
  docs/setup/administrator-account.md
  docs/technical/about.md
  docs/technical/appsettings.md
Labels: documentation

#273 Fix problems with appsettings.json
  CHANGELOG.md
  src/GRA.Web/Startup.cs
  src/GRA.Web/appsettings.json
  src/GRA/ConfigurationKey.cs
Labels: bug, developer

#274 Add metadata for events
  CHANGELOG.md
  src/GRA.Controllers/EventsController.cs
  src/GRA.Controllers/ViewModel/Events/EventsDetailViewModel.cs
  src/GRA.Web/Views/Events/Detail.cshtml
Labels: enhancement

#277 Add trigger activation date
  CHANGELOG.md
  src/GRA.Data/Model/Trigger.cs
  src/GRA.Data/Repository/TriggerRepository.cs
  src/GRA.Domain.Model/Trigger.cs
  src/GRA.Domain.Repository/ITriggerRepository.cs
  src/GRA.Domain.Service/ActivityService.cs
  src/GRA.Web/Areas/MissionControl/Views/Triggers/Detail.cshtml
Labels: enhancement

#284 Fix issue with duplicate initial page loads
  CHANGELOG.md
  src/GRA.Web/Startup.cs
Labels: bug

#285 Fix throwing exception on missing trigger
  CHANGELOG.md
  src/GRA.Controllers/MissionControl/TriggersController.cs
Labels: bug

#286 Fix package selection to use floating versions
  CHANGELOG.md
  src/GRA.CommandLine/GRA.CommandLine.csproj
  src/GRA.Controllers/GRA.Controllers.csproj
  src/GRA.Data.SQLite/GRA.Data.SQLite.csproj
  src/GRA.Data.SqlServer/GRA.Data.SqlServer.csproj
  src/GRA.Data/GRA.Data.csproj
  src/GRA.Domain.Model/GRA.Domain.Model.csproj
  src/GRA.Domain.Report/GRA.Domain.Report.csproj
  src/GRA.Domain.Repository/GRA.Domain.Repository.csproj
  src/GRA.Domain.Service/GRA.Domain.Service.csproj
  src/GRA.Security/GRA.Security.csproj
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/Startup.cs
  src/GRA/GRA.csproj
Labels: developer

#287 Remove activity earned from at a glance report
  CHANGELOG.md
  src/GRA.Domain.Model/StatusSummary.cs
  src/GRA.Domain.Service/ReportService.cs
  src/GRA.Web/Areas/MissionControl/Views/Home/Index.cshtml
Labels: enhancement

#288 Improve site management, add email test
  src/GRA.Controllers/MissionControl/SitesController.cs
  src/GRA.Domain.Service/EmailService.cs
  src/GRA.Web/Areas/MissionControl/Views/Sites/Configuration.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Sites/SocialMedia.cshtml
  src/GRA/SiteSettingDefinitions.cs
Labels: enhancement

#289 Fix change log with info from last commit
  CHANGELOG.md
Labels: developer, documentation

#291 Fix event URL display; ensure role 1 is admin
  CHANGELOG.md
  src/GRA.Domain.Service/RoleService.cs
  src/GRA.Web/Views/Events/Detail.cshtml
  src/GRA.Web/Views/Events/_DetailPartial.cshtml
Labels: bug, enhancement
