Repository MCLD/greatreadingadventure, pull requests merged in 2019-11, with the labels that each got.

#509 Create unit testing and add localization test
  Dockerfile
  GreatReadingAdventure.sln
  TestSettings.testsettings
  src/GRA/Resources/Shared.en.resx
  src/GRA/Resources/Shared.es.resx
  src/GRA/Utility/XmlParser.cs
  test/GRA.Test/GRA.Test.csproj
  test/GRA.Test/VerifyResourcesTest.cs
Labels: developer

#575 Fix carousel start time not updating
  src/GRA.Domain.Service/CarouselService.cs
  src/GRA.Web/Views/Home/Dashboard.cshtml
  src/GRA.Web/Views/Home/Dashboard.es.cshtml
Labels: bug

#568 Add books to book list without logging activity
  src/GRA.Controllers/MissionControl/ParticipantsController.cs
  src/GRA.Controllers/ProfileController.cs
  src/GRA.Data/Repository/BookRepository.cs
  src/GRA.Domain.Repository/IBookRepository.cs
  src/GRA.Domain.Service/ActivityService.cs
  src/GRA.Web/Views/Profile/Books.cshtml
  src/GRA/Annotations.cs
  src/GRA/Resources/Shared.en.resx
  src/GRA/Resources/Shared.es.resx
Labels: awaiting translation, enhancement

#569 Add exit pages
  src/GRA.Controllers/HomeController.cs
  src/GRA.Controllers/JoinController.cs
  src/GRA.Controllers/MissionControl/HomeController.cs
  src/GRA.Controllers/MissionControl/SitesController.cs
  src/GRA.Controllers/MissionControl/SystemInformationController.cs
  src/GRA.Controllers/PerformerRegistration/HomeController.cs
  src/GRA.Controllers/ViewModel/Home/ExitPageViewModel.cs
  src/GRA.Controllers/ViewModel/Join/AuthorizationCodeViewModel.cs
  src/GRA.Controllers/ViewModel/MissionControl/Home/AuthorizationCodeViewModel.cs
  src/GRA.Controllers/ViewModel/MissionControl/SystemInformationViewModel.cs
  src/GRA.Controllers/ViewModel/PerformerRegistration/Home/AuthorizationCodeViewModel.cs
  src/GRA.Domain.Service/UserService.cs
  src/GRA.Web/Areas/MissionControl/Views/Home/AuthorizationCode.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Sites/Configuration.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Sites/Schedule.cshtml
  src/GRA.Web/Areas/MissionControl/Views/SystemInformation/Index.cshtml
  src/GRA.Web/Areas/PerformerRegistration/Views/Home/AuthorizationCode.cshtml
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/Views/Home/Dashboard.cshtml
  src/GRA.Web/Views/Home/Dashboard.es.cshtml
  src/GRA.Web/Views/Home/ExitAccessClosed.cshtml
  src/GRA.Web/Views/Home/ExitAccessClosed.es.cshtml
  src/GRA.Web/Views/Home/ExitBeforeRegistration.cshtml
  src/GRA.Web/Views/Home/ExitBeforeRegistration.es.cshtml
  src/GRA.Web/Views/Home/ExitProgramEnded.cshtml
  src/GRA.Web/Views/Home/ExitProgramEnded.es.cshtml
  src/GRA.Web/Views/Home/ExitProgramOpen.cshtml
  src/GRA.Web/Views/Home/ExitProgramOpen.es.cshtml
  src/GRA.Web/Views/Home/ExitRegistrationOpen.cshtml
  src/GRA.Web/Views/Home/ExitRegistrationOpen.es.cshtml
  src/GRA.Web/Views/Home/IndexAccessClosed.cshtml
  src/GRA.Web/Views/Home/IndexAccessClosed.es.cshtml
  src/GRA.Web/Views/Home/IndexBeforeRegistration.cshtml
  src/GRA.Web/Views/Home/IndexBeforeRegistration.es.cshtml
  src/GRA.Web/Views/Home/IndexProgramEnded.cshtml
  src/GRA.Web/Views/Home/IndexProgramEnded.es.cshtml
  src/GRA.Web/Views/Home/IndexProgramOpen.cshtml
  src/GRA.Web/Views/Home/IndexProgramOpen.es.cshtml
  src/GRA.Web/Views/Home/IndexRegistrationOpen.cshtml
  src/GRA.Web/Views/Home/IndexRegistrationOpen.es.cshtml
  src/GRA.Web/Views/Join/AuthorizationCode.cshtml
  src/GRA.Web/assets/defaultimages/no_avatar.png
  src/GRA.Web/wwwroot/css/gra.css
  src/GRA.Web/wwwroot/css/main.min.css
  src/GRA.Web/wwwroot/images/forest.jpg
  src/GRA.Web/wwwroot/images/forest@2x.jpg
  src/GRA/Annotations.cs
  src/GRA/Defaults.cs
  src/GRA/ViewTemplates.cs
Labels: awaiting translation, enhancement
