Repository MCLD/greatreadingadventure, pull requests merged in 2019-06, with the labels that each got.

#506 Fix capitalization of "share"
  src/GRA.Web/GRA.Web.csproj
  src/GRA/Resources/Shared.en.resx
Labels: bug

#507 Add disable spinners to sign in submit buttons
  CHANGELOG.md
  src/GRA.Web/Views/SignIn/ForgotPassword.cshtml
  src/GRA.Web/Views/SignIn/ForgotUsername.cshtml
  src/GRA.Web/Views/SignIn/Index.cshtml
  src/GRA.Web/Views/SignIn/PasswordRecovery.cshtml
Labels: enhancement

#508 Fix to Insert sample data
  src/GRA.Web/Areas/MissionControl/Views/Flight/Index.cshtml
Labels: bug, developer

#511 Fix performer email addresses to be editable #431
  src/GRA.Domain.Service/PerformerSchedulingService.cs
  src/GRA.Web/Areas/MissionControl/Views/PerformerManagement/PerformerDetails.cshtml
Labels: enhancement

#519 Fix #516 Change badge top score report to one badge
  src/GRA.Domain.Report/BadgeTopScoresReport.cs
  src/GRA.Web/Areas/MissionControl/Views/Reporting/BadgeTopScoresCriteria.cshtml
Labels: bug

#517 Add ability for staff to activate unfired triggers #328
  src/GRA.Controllers/MissionControl/ParticipantsController.cs
Labels: enhancement

#518 Improve HTTP error logging
  src/GRA.Controllers/ErrorController.cs
Labels: developer, enhancement

#521 Fix reporting, report error, AutoMapper call
  src/GRA.CommandLine/Program.cs
  src/GRA.Domain.Service/ReportService.cs
  src/GRA.Web/Areas/MissionControl/Views/Reporting/PrizeRedemptionCountCriteria.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Reporting/Run.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Shared/Job.cshtml
  src/GRA.Web/GRA.Web.csproj
Labels: bug, developer

#522 Adjust initial report response, increase logging
  src/GRA.Domain.Service/ReportService.cs
  src/GRA.Web/Areas/MissionControl/Views/Shared/Job.cshtml
  src/GRA.Web/GRA.Web.csproj
Labels: bug, developer

#523 Send success and cancel URLs with status updates
  src/GRA.Domain.Model/ReportRequest.cs
  src/GRA.Domain.Report/Abstract/BaseReport.cs
  src/GRA.Domain.Service/ReportService.cs
  src/GRA.Web/Areas/MissionControl/Views/Shared/Job.cshtml
  src/GRA.Web/GRA.Web.csproj
Labels: bug, developer

#524 Fix bug that logs "null" for QueryString
  src/GRA.Controllers/ErrorController.cs
  src/GRA.Web/GRA.Web.csproj
Labels: bug, developer

#525 Log trigger awards that take more than 5 seconds
  src/GRA.Controllers/MissionControl/ParticipantsController.cs
  src/GRA.Controllers/SignInController.cs
  src/GRA.Domain.Service/UserService.cs
  src/GRA.Web/GRA.Web.csproj
Labels: developer, enhancement

#526 Fix report redirect for fast reports
  src/GRA.Controllers/Filter/MissionControlFilter.cs
  src/GRA.Controllers/MissionControl/HomeController.cs
  src/GRA.Controllers/MissionControl/ReportingController.cs
  src/GRA.Controllers/ViewModel/MissionControl/Shared/JobViewModel.cs
  src/GRA.Domain.Model/ReportRequest.cs
  src/GRA.Domain.Report/Abstract/BaseReport.cs
  src/GRA.Domain.Service/ActivityService.cs
  src/GRA.Domain.Service/ReportService.cs
  src/GRA.Web/Areas/MissionControl/Views/Shared/Job.cshtml
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/WebSocketHandler.cs
Labels: bug

#527 Improve report status reporting
  src/GRA.Controllers/MissionControl/ReportingController.cs
  src/GRA.Domain.Report/Abstract/BaseReport.cs
  src/GRA.Domain.Report/CommunityExperienceReport.cs
  src/GRA.Web/GRA.Web.csproj
Labels: developer, enhancement

#528 Fix Community Experience report typo for "tabulating"
  src/GRA.Domain.Report/CommunityExperienceReport.cs
Labels: developer, enhancement

#529 Fix badge list client-side evaluation
  CHANGELOG.md
  src/GRA.Data/Repository/TriggerRepository.cs
  src/GRA.Web/Areas/MissionControl/Views/Lookup/_RequirementsPartial.cshtml
Labels: developer, enhancement

#530 Add participant trigger check button
  CHANGELOG.md
  src/GRA.Controllers/MissionControl/ParticipantsController.cs
  src/GRA.Controllers/SignInController.cs
  src/GRA.Domain.Service/ActivityService.cs
  src/GRA.Domain.Service/UserService.cs
  src/GRA.Web/Areas/MissionControl/Views/Participants/UpdatePrizes.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Participants/_ParticipantPartial.cshtml
Labels: enhancement

#531 Fix vendor upload
  src/GRA.Controllers/MissionControl/ParticipantsController.cs
  src/GRA.Controllers/MissionControl/TriggersController.cs
  src/GRA.Controllers/MissionControl/VendorCodesController.cs
  src/GRA.Domain.Model/JobDetailsVendorCodeStatus.cs
  src/GRA.Domain.Model/JobType.cs
  src/GRA.Domain.Service/JobService.cs
  src/GRA.Domain.Service/SiteService.cs
  src/GRA.Domain.Service/VendorCodeService.cs
  src/GRA.Web/Areas/MissionControl/Views/VendorCodes/ImportFile.cshtml
  src/GRA.Web/WebSocketHandler.cs
  src/GRA/Abstract/IPathResolver.cs
  src/GRA/PathResolver.cs
Labels: bug, enhancement

#533 Change avatar insert to use the job system
  src/GRA.Controllers/MissionControl/AvatarsController.cs
  src/GRA.Domain.Model/JobDetailsAvatarImport.cs
  src/GRA.Domain.Model/JobType.cs
  src/GRA.Domain.Service/AvatarService.cs
  src/GRA.Domain.Service/JobService.cs
  src/GRA.Web/Areas/MissionControl/Views/Participants/Books.cshtml
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/Views/Profile/Books.cshtml
Labels: enhancement

#534 Change household import to use the job system
  CHANGELOG.md
  src/GRA.Controllers/MissionControl/ParticipantsController.cs
  src/GRA.Domain.Model/JobDetailsHouseholdImport.cs
  src/GRA.Domain.Model/JobType.cs
  src/GRA.Domain.Report/RegistrationsAchieversBySchoolReport.cs
  src/GRA.Domain.Service/JobService.cs
  src/GRA.Domain.Service/UserImportService.cs
  src/GRA.Domain.Service/UserService.cs
  src/GRA.Domain.Service/VendorCodeService.cs
  src/GRA.Web/Areas/MissionControl/Views/Participants/UpdateGroup.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Schools/Index.cshtml
Labels: bug, enhancement

#535 Newness of posts in news categories #434
  src/GRA.Controllers/MissionControl/HomeController.cs
  src/GRA.Controllers/ViewModel/MissionControl/Home/AtAGlanceViewModel.cs
  src/GRA.Data.SqlServer/Migrations/20190626173615_last-post-date.Designer.cs
  src/GRA.Data.SqlServer/Migrations/20190626173615_last-post-date.cs
  src/GRA.Data/Model/NewsCategory.cs
  src/GRA.Data/Repository/NewsCategoryRepository.cs
  src/GRA.Domain.Model/NewsCategory.cs
  src/GRA.Domain.Repository/INewsCategoryRepository.cs
  src/GRA.Domain.Service/NewsService.cs
  src/GRA.Web/Areas/MissionControl/Views/Home/Index.cshtml
  src/GRA.Web/GRA.Web.csproj
Labels: enhancement
