Repository MCLD/greatreadingadventure, pull requests merged in 2019-04, with the labels that each got.

#451 Add address map
  src/GRA.Controllers/MissionControl/EventsController.cs
  src/GRA.Controllers/MissionControl/SystemsController.cs
  src/GRA.Controllers/ViewModel/MissionControl/Events/EventsDetailViewModel.cs
  src/GRA.Controllers/ViewModel/MissionControl/Events/LocationsListViewModel.cs
  src/GRA.Controllers/ViewModel/MissionControl/Systems/BranchesListViewModel.cs
  src/GRA.Web/Areas/MissionControl/Views/Events/Create.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Events/Edit.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Events/Locations.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Systems/Branches.cshtml
Labels: enhancement

#462 Add missing service registrations
  src/GRA.Web/Startup.cs
Labels: bug

#453 Minor fixes
  .gitattributes
  CHANGELOG.md
  src/GRA.CommandLine/GRA.CommandLine.csproj
  src/GRA.Controllers/ChallengesController.cs
  src/GRA.Controllers/GRA.Controllers.csproj
  src/GRA.Data.SQLite/GRA.Data.SQLite.csproj
  src/GRA.Data.SqlServer/GRA.Data.SqlServer.csproj
  src/GRA.Data/GRA.Data.csproj
  src/GRA.Data/Model/PsProgram.cs
  src/GRA.Domain.Report/PrizeRedemptionCountReport.cs
  src/GRA.Domain.Report/VendorCodeDonationsReport.cs
  src/GRA.Domain.Service/CategoryService.cs
  src/GRA.Domain.Service/EventService.cs
  src/GRA.Domain.Service/GRA.Domain.Service.csproj
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/Program.cs
  src/GRA.Web/Views/Avatar/Index.cshtml
  src/GRA.Web/wwwroot/js/main.min.js
  src/GRA.Web/wwwroot/js/markdown.min.js
Labels: bug, enhancement

#466 Update MailKit/MimeKit; .gitattribute min files
  .gitattributes
  src/GRA.Domain.Service/GRA.Domain.Service.csproj
Labels: developer, enhancement

#467 Fix Docker builds if image is not retained
  Dockerfile
  docker-build.bash
  src/GRA.Web/GRA.Web.csproj
Labels: developer, enhancement

#468 Fix Dockerfile typo
  Dockerfile
Labels: bug, developer

#469 Add user join badge checking
  CHANGELOG.md
  src/GRA.Controllers/SignInController.cs
  src/GRA.Data/Repository/BadgeRepository.cs
  src/GRA.Domain.Repository/IBadgeRepository.cs
  src/GRA.Domain.Service/UserService.cs
  src/GRA.Web/GRA.Web.csproj
Labels: enhancement

#471 Add avatar unavailable items list
  CHANGELOG.md
  src/GRA.Controllers/MissionControl/AvatarsController.cs
  src/GRA.Controllers/ViewModel/MissionControl/Avatar/ItemsListViewModel.cs
  src/GRA.Data/Repository/AvatarBundleRepository.cs
  src/GRA.Data/Repository/AvatarItemRepository.cs
  src/GRA.Domain.Model/AvatarLayer.cs
  src/GRA.Domain.Model/Filters/AvatarFilter.cs
  src/GRA.Domain.Repository/IAvatarItemRepository.cs
  src/GRA.Domain.Service/AvatarService.cs
  src/GRA.Web/Areas/MissionControl/Views/Avatars/BundleDetail.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Avatars/Index.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Avatars/Layer.cshtml
Labels: enhancement

#472 Fix startup template copying
  src/GRA.Controllers/HomeController.cs
  src/GRA.Domain.Service/TemplateService.cs
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/Program.cs
  src/GRA.Web/Startup.cs
  src/GRA.Web/Web.cs
  src/GRA/ViewTemplates.cs
Labels: bug

#473 Add i18n to front-end events UI; improve Spanish
  src/GRA.Controllers/ViewModel/Events/EventsListViewModel.cs
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/Views/Events/Index.cshtml
  src/GRA.Web/Views/Join/Step3.cshtml
  src/GRA/Annotations.cs
  src/GRA/DisplayNames.cs
  src/GRA/Resources/Shared.en.resx
  src/GRA/Resources/Shared.es.resx
Labels: enhancement, i18n

#475 Add landing page preview
  CHANGELOG.md
  src/GRA.Controllers/HomeController.cs
  src/GRA.Web/GRA.Web.csproj
Labels: enhancement

#476 Improve internationalization
  src/GRA.Controllers/AvatarController.cs
  src/GRA.Controllers/Base/Controller.cs
  src/GRA.Controllers/ChallengesController.cs
  src/GRA.Controllers/EventsController.cs
  src/GRA.Controllers/Filter/SiteFilter.cs
  src/GRA.Controllers/HomeController.cs
  src/GRA.Controllers/ItemKey.cs
  src/GRA.Controllers/MissionControl/ParticipantsController.cs
  src/GRA.Controllers/ProfileController.cs
  src/GRA.Controllers/ViewModel/Challenges/ChallengeDetailViewModel.cs
  src/GRA.Controllers/ViewModel/Challenges/TaskDetailViewModel.cs
  src/GRA.Controllers/ViewModel/MissionControl/Participants/ParticipantsAddViewModel.cs
  src/GRA.Domain.Model/User.cs
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/Views/Avatar/Index.cshtml
  src/GRA.Web/Views/Avatar/Share.cshtml
  src/GRA.Web/Views/Challenges/Detail.cshtml
  src/GRA.Web/Views/Challenges/Index.cshtml
  src/GRA.Web/Views/Events/Detail.cshtml
  src/GRA.Web/Views/Events/Index.cshtml
  src/GRA.Web/Views/Events/_DetailPartial.cshtml
  src/GRA.Web/Views/Profile/Index.cshtml
  src/GRA.Web/Views/Shared/_Layout.cshtml
  src/GRA.Web/wwwroot/images/no_avatar.png
  src/GRA/Annotations.cs
  src/GRA/DisplayNames.cs
  src/GRA/Resources/Shared.en.resx
  src/GRA/Resources/Shared.es.resx
Labels: enhancement, i18n
