Repository MCLD/greatreadingadventure, pull requests merged in 2019-12, with the labels that each got.

#577 Improve Spanish translations
  src/GRA/Resources/Shared.es.resx
Labels: enhancement, i18n

#580 Fix broken Spanish translations
  src/GRA/Resources/Shared.es.resx
Labels: enhancement, i18n

#581 Fix escaped double quotes in .resx
  src/GRA/Resources/Shared.en.resx
  src/GRA/Resources/Shared.es.resx
Labels: bug, i18n

#584 Fix client-side evaluation on logging activity with a title
  src/GRA.Data/Repository/BookRepository.cs
  src/GRA.Web/GRA.Web.csproj
Labels: bug
