Repository MCLD/greatreadingadventure, pull requests merged in 2019-02, with the labels that each got.

#425 Bug fixes and improvements
  CHANGELOG.md
  Dockerfile
  docker-build.bash
  src/GRA.CommandLine/GRA.CommandLine.csproj
  src/GRA.Controllers/Base/Controller.cs
  src/GRA.Controllers/Base/MCController.cs
  src/GRA.Controllers/EventsController.cs
  src/GRA.Controllers/Filter/EventUrlFilter.cs
  src/GRA.Controllers/Filter/NotificationFilter.cs
  src/GRA.Controllers/Filter/SessionTimeoutFilter.cs
  src/GRA.Controllers/Filter/SiteFilter.cs
  src/GRA.Controllers/Filter/UnauthenticatedFilter.cs
  src/GRA.Controllers/GRA.Controllers.csproj
  src/GRA.Controllers/MissionControl/ChallengesController.cs
  src/GRA.Controllers/MissionControl/EventsController.cs
  src/GRA.Controllers/MissionControl/FlightController.cs
  src/GRA.Controllers/MissionControl/HomeController.cs
  src/GRA.Controllers/MissionControl/PerformerManagementController.cs
  src/GRA.Controllers/MissionControl/ProgramsController.cs
  src/GRA.Controllers/MissionControl/SystemInformationController.cs
  src/GRA.Controllers/MissionControl/TriggersController.cs
  src/GRA.Controllers/PerformerRegistration/HomeController.cs
  src/GRA.Controllers/ViewModel/MissionControl/SystemInformationViewModel.cs
  src/GRA.Domain.Service/GRA.Domain.Service.csproj
  src/GRA.Domain.Service/SampleDataService.cs
  src/GRA.Web/Areas/MissionControl/Views/Flight/Index.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Shared/_Layout.cshtml
  src/GRA.Web/Areas/MissionControl/Views/SystemInformation/Index.cshtml
Labels: bug

#428 Fix EF client-side evaluations
  src/GRA.Data/Repository/PsPerformerRepository.cs
  src/GRA.Data/Repository/PsProgramRepository.cs
  src/GRA.Data/Repository/RequiredQuestionnaireRepository.cs
  src/GRA.Data/Repository/UserLogRepository.cs
Labels: bug, developer, enhancement

#432 Fix performer selection secret code entry
  src/GRA.Controllers/MissionControl/PerformerManagementController.cs
  src/GRA.Domain.Service/PerformerSchedulingService.cs
Labels: bug

#433 Update references and fix targets
  src/GRA.CommandLine/GRA.CommandLine.csproj
  src/GRA.Controllers/GRA.Controllers.csproj
  src/GRA.Data.SQLite/GRA.Data.SQLite.csproj
  src/GRA.Data.SqlServer/GRA.Data.SqlServer.csproj
  src/GRA.Data/GRA.Data.csproj
  src/GRA.Domain.Service/GRA.Domain.Service.csproj
  src/GRA.Web/GRA.Web.csproj
Labels: developer, enhancement

#438 Fix editing point translations
  CHANGELOG.md
  src/GRA.Web/Areas/MissionControl/Views/Programs/PointTranslationDetail.cshtml
  src/GRA.Web/GRA.Web.csproj
Labels: bug
