Repository MCLD/greatreadingadventure, pull requests merged in 2019-07, with the labels that each got.

#536 Tune bulk email operations
  src/GRA.Domain.Service/EmailBulkService.cs
  src/GRA.Web/GRA.Web.csproj
Labels: enhancement

#537 Fix avatar body color selection error
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/Views/Avatar/Index.cshtml
Labels: bug

#538 Fix community experience report
  CHANGELOG.md
  src/GRA.Data/Repository/EventRepository.cs
Labels: bug, developer

#539 Add bulk vendor code redemption
  CHANGELOG.md
  src/GRA.Controllers/MissionControl/ParticipantsController.cs
  src/GRA.Controllers/ViewModel/MissionControl/Participants/HouseholdListViewModel.cs
  src/GRA.Data/Repository/GroupInfoRepository.cs
  src/GRA.Data/Repository/VendorCodeRepository.cs
  src/GRA.Domain.Model/Permission.cs
  src/GRA.Domain.Model/Policy.cs
  src/GRA.Domain.Report/GroupVendorCodeReport.cs
  src/GRA.Domain.Repository/IVendorCodeRepository.cs
  src/GRA.Domain.Service/VendorCodeService.cs
  src/GRA.Web/Areas/MissionControl/Views/Participants/Household.cshtml
  src/GRA.Web/GRA.Web.csproj
Labels: enhancement

#540 Fix group vendor code report excel export
  src/GRA.Controllers/MissionControl/ReportingController.cs
Labels: bug

#550 Fix reporting SQL IN clause error
  CHANGELOG.md
  src/GRA.Data/Repository/UserLogRepository.cs
Labels: bug
