Repository MCLD/greatreadingadventure, pull requests merged in 2019-05, with the labels that each got.

#477 Fix password recovery validation error handling
  CHANGELOG.md
  src/GRA.Controllers/JoinController.cs
  src/GRA.Controllers/SignInController.cs
  src/GRA.Controllers/ViewModel/Join/SinglePageViewModel.cs
  src/GRA.Controllers/ViewModel/Join/Step3ViewModel.cs
  src/GRA.Controllers/ViewModel/SignIn/PasswordRecoveryViewModel.cs
  src/GRA/DisplayNames.cs
  src/GRA/GraPasswordValidationException.cs
  src/GRA/PasswordValidator.cs
Labels: bug, i18n

#479 Fix setting challenge task type
  CHANGELOG.md
  src/GRA.Domain.Service/ChallengeService.cs
  src/GRA.Web/Areas/MissionControl/Views/Challenges/Edit.cshtml
  src/GRA.Web/Views/Challenges/Detail.cshtml
Labels: bug

#480 Internationalization and bug fixes
  src/GRA.Controllers/Filter/SiteFilter.cs
  src/GRA.Controllers/JoinController.cs
  src/GRA.Controllers/MissionControl/NewsController.cs
  src/GRA.Controllers/ProfileController.cs
  src/GRA.Controllers/SignInController.cs
  src/GRA.Controllers/ViewModel/Events/EventsListViewModel.cs
  src/GRA.Controllers/ViewModel/Home/DashboardViewModel.cs
  src/GRA.Controllers/ViewModel/Join/SinglePageViewModel.cs
  src/GRA.Controllers/ViewModel/Join/Step1ViewModel.cs
  src/GRA.Controllers/ViewModel/Join/Step2ViewModel.cs
  src/GRA.Controllers/ViewModel/Join/Step3ViewModel.cs
  src/GRA.Controllers/ViewModel/Profile/ChangePasswordViewModel.cs
  src/GRA.Controllers/ViewModel/Profile/HouseholdExistingViewModel.cs
  src/GRA.Controllers/ViewModel/SignIn/PasswordRecoveryViewModel.cs
  src/GRA.Controllers/ViewModel/SignIn/SignInViewModel.cs
  src/GRA.Domain.Model/Book.cs
  src/GRA.Domain.Model/GroupInfo.cs
  src/GRA.Domain.Model/Metadata/DisplayNames.cs
  src/GRA.Domain.Model/Metadata/ErrorMessages.cs
  src/GRA.Domain.Service/EmailService.cs
  src/GRA.Domain.Service/NewsService.cs
  src/GRA.Domain.Service/UserService.cs
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/Views/Avatar/Index.cshtml
  src/GRA.Web/Views/Challenges/Index.cshtml
  src/GRA.Web/Views/Home/Dashboard.cshtml
  src/GRA.Web/Views/Home/Dashboard.es.cshtml
  src/GRA.Web/Views/Home/IndexAccessClosed.cshtml
  src/GRA.Web/Views/Home/IndexAccessClosed.es.cshtml
  src/GRA.Web/Views/Home/IndexBeforeRegistration.cshtml
  src/GRA.Web/Views/Home/IndexBeforeRegistration.es.cshtml
  src/GRA.Web/Views/Home/IndexProgramEnded.cshtml
  src/GRA.Web/Views/Home/IndexProgramEnded.es.cshtml
  src/GRA.Web/Views/Home/IndexProgramOpen.cshtml
  src/GRA.Web/Views/Home/IndexProgramOpen.es.cshtml
  src/GRA.Web/Views/Home/IndexRegistrationOpen.cshtml
  src/GRA.Web/Views/Home/IndexRegistrationOpen.es.cshtml
  src/GRA.Web/Views/Join/Index.cshtml
  src/GRA.Web/Views/Join/Step1.cshtml
  src/GRA.Web/Views/Join/Step2.cshtml
  src/GRA.Web/Views/Profile/AddExistingParticipant.cshtml
  src/GRA.Web/Views/Profile/Books.cshtml
  src/GRA.Web/Views/Profile/ChangePassword.cshtml
  src/GRA.Web/Views/Profile/GroupDetails.cshtml
  src/GRA.Web/Views/Profile/GroupUpgrade.cshtml
  src/GRA.Web/Views/Profile/History.cshtml
  src/GRA.Web/Views/Profile/Household.cshtml
  src/GRA.Web/Views/Profile/Index.cshtml
  src/GRA.Web/Views/Profile/_ProfilePartial.cshtml
  src/GRA.Web/Views/Shared/_Layout.cshtml
  src/GRA.Web/Views/Shared/_SchoolSelectionPartial.cshtml
  src/GRA.Web/Views/SignIn/ForgotPassword.cshtml
  src/GRA.Web/Views/SignIn/ForgotUsername.cshtml
  src/GRA.Web/Views/SignIn/Index.cshtml
  src/GRA/Annotations.cs
  src/GRA/Resources/Shared.en.resx
  src/GRA/Resources/Shared.es.resx
  src/GRA/ViewTemplates.cs
Labels: bug, enhancement, i18n

#481 Fix localization exceptions
  src/GRA.Controllers/HomeController.cs
  src/GRA.Web/Views/Challenges/Detail.cshtml
Labels: bug

#482 Internationalize 404 page and mail
  .codacy.yaml
  src/GRA.Controllers/MailController.cs
  src/GRA.Controllers/ViewModel/Join/SinglePageViewModel.cs
  src/GRA.Controllers/ViewModel/Join/Step1ViewModel.cs
  src/GRA.Controllers/ViewModel/Join/Step2ViewModel.cs
  src/GRA.Controllers/ViewModel/Mail/MailCreateViewModel.cs
  src/GRA.Domain.Model/Mail.cs
  src/GRA.Domain.Model/Metadata/DisplayNames.cs
  src/GRA.Domain.Model/Metadata/ErrorMessages.cs
  src/GRA.Domain.Model/User.cs
  src/GRA.Web/Views/Error/404.cshtml
  src/GRA.Web/Views/Mail/Index.cshtml
  src/GRA.Web/Views/Mail/Read.cshtml
  src/GRA.Web/Views/Mail/Reply.cshtml
  src/GRA.Web/Views/Mail/Send.cshtml
  src/GRA/Annotations.cs
  src/GRA/Resources/Shared.en.resx
Labels: enhancement, i18n

#483 Remove .codacy.yaml
  .codacy.yaml
Labels: bug, developer

#484 Add challenge created by text
  CHANGELOG.md
  src/GRA.Controllers/MissionControl/ChallengesController.cs
  src/GRA.Controllers/ViewModel/MissionControl/Challenges/ChallengesDetailViewModel.cs
  src/GRA.Web/Areas/MissionControl/Views/Challenges/Edit.cshtml
Labels: enhancement

#485 Internationalize households
  src/GRA.Controllers/Base/Controller.cs
  src/GRA.Controllers/Filter/SessionTimeoutFilterAttribute.cs
  src/GRA.Controllers/ProfileController.cs
  src/GRA.Controllers/ViewComponents/DisplayNotificationsViewComponent.cs
  src/GRA.Controllers/ViewModel/MissionControl/Participants/HouseholdAddViewModel.cs
  src/GRA.Controllers/ViewModel/MissionControl/Participants/ParticipantsAddViewModel.cs
  src/GRA.Controllers/ViewModel/Profile/HouseholdAddViewModel.cs
  src/GRA.Controllers/ViewModel/Profile/HouseholdListViewModel.cs
  src/GRA.Controllers/ViewModel/Profile/HouseholdRegisterViewModel.cs
  src/GRA.Controllers/ViewModel/Profile/HouseholdRemoveViewModel.cs
  src/GRA.Controllers/ViewModel/Shared/SchoolSelectionViewModel.cs
  src/GRA.Data/Model/Notification.cs
  src/GRA.Domain.Model/Metadata/DisplayNames.cs
  src/GRA.Domain.Model/Notification.cs
  src/GRA.Domain.Model/School.cs
  src/GRA.Domain.Model/User.cs
  src/GRA.Domain.Service/UserService.cs
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/Startup.cs
  src/GRA.Web/Views/Home/Dashboard.cshtml
  src/GRA.Web/Views/Home/Dashboard.es.cshtml
  src/GRA.Web/Views/Profile/AddExistingParticipant.cshtml
  src/GRA.Web/Views/Profile/Household.cshtml
  src/GRA.Web/Views/Profile/HouseholdAdd.cshtml
  src/GRA.Web/Views/Shared/Components/DisplayNotifications/Alert.cshtml
  src/GRA.Web/Views/Shared/Components/DisplayNotifications/Modal.cshtml
  src/GRA.Web/Views/Shared/_Layout.cshtml
  src/GRA/Annotations.cs
  src/GRA/Resources/Shared.en.resx
Labels: enhancement, i18n

#486 Fix authentication code and sign-in redirects
  docs/technical/appsettings.md
  src/GRA.CommandLine/GRA.CommandLine.csproj
  src/GRA.CommandLine/Program.cs
  src/GRA.Controllers/Base/Controller.cs
  src/GRA.Controllers/Filter/SiteFilter.cs
  src/GRA.Controllers/GRA.Controllers.csproj
  src/GRA.Controllers/HomeController.cs
  src/GRA.Controllers/MissionControl/HomeController.cs
  src/GRA.Controllers/PerformerRegistration/HomeController.cs
  src/GRA.Controllers/SignInController.cs
  src/GRA.Controllers/TempDataKey.cs
  src/GRA.Data/GRA.Data.csproj
  src/GRA.Domain.Report/GRA.Domain.Report.csproj
  src/GRA.Domain.Service/GRA.Domain.Service.csproj
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/LogConfig.cs
  src/GRA.Web/Startup.cs
  src/GRA.Web/appsettings.json
  src/GRA/GRA.csproj
  src/GRA/GraFatalException.cs
  src/GRA/Version.cs
Labels: bug, enhancement

#487 Remove .codacy.yaml file
  .codacy.yaml
Labels: developer

#488 Add Serilog expressions back in
  src/GRA.Web/GRA.Web.csproj
Labels: bug, developer

#490 Improve http error logging
  src/GRA.Controllers/ErrorController.cs
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/Startup.cs
Labels: enhancement

#491 Change household import to use excel spreadsheet
  CHANGELOG.md
  src/GRA.Controllers/Base/MCController.cs
  src/GRA.Controllers/MissionControl/ParticipantsController.cs
  src/GRA.Controllers/ViewModel/MissionControl/Participants/HouseholdImportViewModel.cs
  src/GRA.Domain.Service/UserImportService.cs
  src/GRA.Web/Areas/MissionControl/Views/Participants/HouseholdImport.cshtml
  src/GRA.Web/GRA.Web.csproj
Labels: enhancement

#492 Add additional Spanish translations; update dev
  Dockerfile
  GreatReadingAdventure.sln
  dev/README.md
  dev/docker.md
  dev/initial-developer-setup.md
  dev/project-organization.md
  src/GRA/Resources/Shared.es.resx
Labels: developer, i18n

#496 Fix add new family/group member text
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/Views/Profile/HouseholdAdd.cshtml
Labels: enhancement

#497 Fix Dockerfile error - use ASP.NET Core runtime
  Dockerfile
Labels: bug, developer

#498 Move back to RollingLog due to issues
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/LogConfig.cs
Labels: bug, developer

#499 Add back Familia to the Spanish resource file
  src/GRA.Web/GRA.Web.csproj
  src/GRA/Resources/Shared.es.resx
Labels: i18n

#500 Fix logic error in full name display
  src/GRA.Domain.Model/User.cs
  src/GRA.Web/GRA.Web.csproj
Labels: bug

#501 Fix household import age handling
  src/GRA.Domain.Service/UserImportService.cs
  src/GRA.Web/GRA.Web.csproj
Labels: bug

#503 Add token unsubscribing same emails
  src/GRA.Controllers/HomeController.cs
  src/GRA.Data/Repository/UserRepository.cs
  src/GRA.Domain.Repository/IUserRepository.cs
  src/GRA.Domain.Service/EmailManagementService.cs
  src/GRA.Web/Areas/MissionControl/Views/Participants/EmailSubscriptionLog.cshtml
Labels: enhancement

#504 Add assemblies to AutoMapper service injection
  CHANGELOG.md
  src/GRA.Web/Startup.cs
Labels: developer

#505 Add template options to bulk emails
  src/GRA.Domain.Service/EmailService.cs
  src/GRA.Web/GRA.Web.csproj
Labels: enhancement
