Repository MCLD/greatreadingadventure, pull requests merged in 2019-01, with the labels that each got.

#403 Move favicons to shared/content from wwwroot
  CHANGELOG.md
  docs/setup/customizing-the-look-and-feel.md
  src/GRA.Domain.Service/TemplateService.cs
  src/GRA.Web/Areas/MissionControl/Views/Home/AuthorizationCode.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Shared/_Layout.cshtml
  src/GRA.Web/Areas/PerformerRegistration/Views/Home/AuthorizationCode.cshtml
  src/GRA.Web/Areas/PerformerRegistration/Views/Shared/_Layout.cshtml
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/Startup.cs
  src/GRA.Web/Views/Shared/_Layout.cshtml
  src/GRA.Web/Web.cs
  src/GRA.Web/assets/defaultsocial/android-chrome-192x192.png
  src/GRA.Web/assets/defaultsocial/android-chrome-384x384.png
  src/GRA.Web/assets/defaultsocial/apple-touch-icon.png
  src/GRA.Web/assets/defaultsocial/browserconfig.xml
  src/GRA.Web/assets/defaultsocial/favicon-16x16.png
  src/GRA.Web/assets/defaultsocial/favicon-32x32.png
  src/GRA.Web/assets/defaultsocial/favicon-96x96.png
  src/GRA.Web/assets/defaultsocial/favicon.ico
  src/GRA.Web/assets/defaultsocial/mstile-150x150.png
  src/GRA.Web/assets/defaultsocial/safari-pinned-tab.svg
  src/GRA.Web/assets/defaultsocial/site.webmanifest
  src/GRA.Web/wwwroot/android-chrome-192x192.png
  src/GRA.Web/wwwroot/android-chrome-384x384.png
  src/GRA.Web/wwwroot/apple-touch-icon-precomposed.png
  src/GRA.Web/wwwroot/apple-touch-icon.png
  src/GRA.Web/wwwroot/browserconfig.xml
  src/GRA.Web/wwwroot/favicon.png
  src/GRA.Web/wwwroot/manifest.json
  src/GRA.Web/wwwroot/mstile-150x150.png
  src/GRA.Web/wwwroot/safari-pinned-tab.svg
Labels: enhancement

#404 Fix favicon and performer management issues
  src/GRA.Controllers/MissionControl/PerformerManagementController.cs
  src/GRA.Domain.Service/TemplateService.cs
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/assets/defaultfavicon/android-chrome-192x192.png
  src/GRA.Web/assets/defaultfavicon/android-chrome-384x384.png
  src/GRA.Web/assets/defaultfavicon/apple-touch-icon.png
  src/GRA.Web/assets/defaultfavicon/browserconfig.xml
  src/GRA.Web/assets/defaultfavicon/favicon-16x16.png
  src/GRA.Web/assets/defaultfavicon/favicon-32x32.png
  src/GRA.Web/assets/defaultfavicon/favicon-96x96.png
  src/GRA.Web/assets/defaultfavicon/favicon.ico
  src/GRA.Web/assets/defaultfavicon/mstile-150x150.png
  src/GRA.Web/assets/defaultfavicon/safari-pinned-tab.svg
  src/GRA.Web/assets/defaultfavicon/site.webmanifest
Labels: bug

#405 Fix ajax action parameters
  src/GRA.Controllers/MissionControl/PerformerManagementController.cs
  src/GRA.Controllers/MissionControl/PerformerSchedulingController.cs
  src/GRA.Web/Areas/MissionControl/Views/PerformerManagement/_PerformerCalendarPartial.cshtml
  src/GRA.Web/Areas/MissionControl/Views/PerformerScheduling/SelectProgram.cshtml
Labels: bug

#407 Fix performer registration controllers
  src/GRA.Controllers/MissionControl/PerformerManagementController.cs
  src/GRA.Controllers/PerformerRegistration/HomeController.cs
Labels: bug

#408 Fix performer registration, dashboard display
  src/GRA.Controllers/HomeController.cs
  src/GRA.Controllers/ViewModel/Home/DashboardViewModel.cs
  src/GRA.Domain.Service/PerformerSchedulingService.cs
  src/GRA.Web/Views/Home/Dashboard.cshtml
Labels: bug, enhancement

#409 Fix performer program deletion, update references
  src/GRA.CommandLine/GRA.CommandLine.csproj
  src/GRA.Controllers/MissionControl/PerformerManagementController.cs
  src/GRA.Controllers/MissionControl/PerformerSchedulingController.cs
  src/GRA.Domain.Service/GRA.Domain.Service.csproj
  src/GRA.Domain.Service/PerformerSchedulingService.cs
Labels: bug

#410 Fix typo, use DateTime provider, Ajax status
  src/GRA.Controllers/Base/Controller.cs
  src/GRA.Controllers/Filter/SessionTimeoutFilter.cs
  src/GRA.Controllers/MissionControl/PerformerManagementController.cs
  src/GRA.Controllers/ViewModel/MissionControl/PerformerManagement/PerformerManagementPartialViewModel.cs
  src/GRA.Controllers/ViewModel/MissionControl/PerformerManagement/StatusViewModel.cs
  src/GRA.Data/Repository/PsKitRepository.cs
  src/GRA.Data/Repository/PsPerformerRepository.cs
  src/GRA.Data/Repository/PsProgramRepository.cs
  src/GRA.Domain.Repository/IPsKitRepository.cs
  src/GRA.Domain.Repository/IPsPerformerRepository.cs
  src/GRA.Domain.Repository/IPsProgramRepository.cs
  src/GRA.Domain.Service/PerformerSchedulingService.cs
  src/GRA.Web/Areas/MissionControl/Views/PerformerManagement/Index.cshtml
  src/GRA.Web/Areas/MissionControl/Views/PerformerManagement/_PerformerManagementPartial.cshtml
Labels: bug, enhancement

#412 Fix paths to Slick for dashboard carousels
  src/GRA.Web/Areas/MissionControl/Views/Carousels/Detail.cshtml
  src/GRA.Web/Views/Home/Dashboard.cshtml
  src/GRA.Web/bundleconfig.json
  src/GRA.Web/wwwroot/js/slick.min.js
Labels: bug

#414 Update package references; fix StackExchange.Redis
  src/GRA.CommandLine/GRA.CommandLine.csproj
  src/GRA.Controllers/GRA.Controllers.csproj
  src/GRA.Data.SQLite/GRA.Data.SQLite.csproj
  src/GRA.Data.SqlServer/GRA.Data.SqlServer.csproj
  src/GRA.Data/GRA.Data.csproj
  src/GRA.Domain.Service/GRA.Domain.Service.csproj
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/Startup.cs
Labels: developer

#417 Fix reference to Microsoft.AspNetCore.StaticFiles
  src/GRA.Controllers/GRA.Controllers.csproj
Labels: bug

#419 Fix logging level of recovery misses to info
  CHANGELOG.md
  src/GRA.Controllers/SignInController.cs
Labels: enhancement

#420 Fix join with authorization code redirect
  CHANGELOG.md
  src/GRA.Controllers/HomeController.cs
  src/GRA.Controllers/SignInController.cs
Labels: enhancement

#423 Fix private file handling, improve Mission Control dashboard
  .gitignore
  CHANGELOG.md
  src/GRA.Controllers/MissionControl/FilesController.cs
  src/GRA.Controllers/MissionControl/HomeController.cs
  src/GRA.Controllers/SignInController.cs
  src/GRA.Controllers/ViewModel/MissionControl/Home/AtAGlanceReport.cs
  src/GRA.Controllers/ViewModel/MissionControl/Home/AtAGlanceViewModel.cs
  src/GRA.Data/Repository/NewsPostRepository.cs
  src/GRA.Domain.Model/StatusSummary.cs
  src/GRA.Domain.Repository/INewsPostRepository.cs
  src/GRA.Domain.Service/NewsService.cs
  src/GRA.Domain.Service/ReportService.cs
  src/GRA.Web/Areas/MissionControl/Views/Home/Index.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Shared/_Layout.cshtml
  src/GRA.Web/wwwroot/css/missioncontrol.css
  src/GRA.Web/wwwroot/css/missioncontrol.min.css
  src/GRA/Abstract/IPathResolver.cs
  src/GRA/CacheKey.cs
  src/GRA/PathResolver.cs
Labels: bug, enhancement
