Repository MCLD/greatreadingadventure, pull requests merged in 2020-05, with the labels that each got.

#631 Fix avatar item selection issues
  CHANGELOG.md
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/Views/Avatar/Index.cshtml
Labels: bug

#633 Fix overflow on JobService reference
  src/GRA.Domain.Service/JobService.cs
  src/GRA.Web/GRA.Web.csproj
Labels: bug, developer

#617 Improve authorization code process
  src/GRA.Controllers/JoinController.cs
  src/GRA.Controllers/MissionControl/HomeController.cs
  src/GRA.Web/GRA.Web.csproj
  src/GRA/Annotations.cs
  src/GRA/Resources/Shared.en.resx
  src/GRA/Resources/Shared.es.resx
Labels: awaiting translation, enhancement

#639 Fix display of dependent triggers
  src/GRA.Controllers/MissionControl/EventsController.cs
  src/GRA.Controllers/MissionControl/TriggersController.cs
  src/GRA.Data/Repository/TriggerRepository.cs
  src/GRA.Domain.Repository/ITriggerRepository.cs
  src/GRA.Domain.Service/TriggerService.cs
  src/GRA.Web/GRA.Web.csproj
Labels: enhancement

#642 Increase version number for streaming events
  src/GRA.Web/GRA.Web.csproj
Labels: developer

#643 Remove ReportingController overload
  src/GRA.Controllers/MissionControl/ReportingController.cs
  src/GRA.Web/GRA.Web.csproj
Labels: bug, developer

#644 Fix streaming event date searching; translations
  src/GRA.Controllers/MissionControl/EventsController.cs
  src/GRA.Data/Repository/EventRepository.cs
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/Views/Events/Detail.cshtml
  src/GRA.Web/Views/Events/Index.cshtml
  src/GRA.Web/Views/Events/_DetailPartial.cshtml
  src/GRA/Annotations.cs
  src/GRA/Resources/Shared.en.resx
  src/GRA/Resources/Shared.es.resx
Labels: bug

#649 Remove shared/templates on clean or build
  src/GRA.Web/GRA.Web.csproj
Labels: developer, enhancement

#652 Fix bug in export of reminder subscribers
  src/GRA.Data/Repository/EmailReminderRepository.cs
  src/GRA.Web/GRA.Web.csproj
Labels: bug
