Repository MCLD/greatreadingadventure, pull requests merged in 2020-10, with the labels that each got.

#673 Update dependencies; force MC to default language
  src/GRA.CommandLine/GRA.CommandLine.csproj
  src/GRA.Controllers/GRA.Controllers.csproj
  src/GRA.Controllers/MissionControl/HomeController.cs
  src/GRA.Data/GRA.Data.csproj
  src/GRA.Data/Repository/EmailTemplateRepository.cs
  src/GRA.Domain.Service/EmailService.cs
  src/GRA.Domain.Service/EventImportService.cs
  src/GRA.Domain.Service/GRA.Domain.Service.csproj
  src/GRA.Domain.Service/SchoolImportService.cs
  src/GRA.Domain.Service/UserImportService.cs
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/LogConfig.cs
  src/GRA.Web/Startup.cs
  test/GRA.Test/GRA.Test.csproj
Labels: developer, enhancement, hacktoberfest-accepted

#674 Fix GitHub Action environment configuration
  .github/workflows/main.yml
Labels: developer

#677 Fix commandline version of bundler/minifier
  src/GRA.Web/GRA.Web.csproj
Labels: developer, hacktoberfest-accepted

#655 Add badge image max size
  CHANGELOG.md
  src/GRA.Controllers/AvatarController.cs
  src/GRA.Controllers/GRA.Controllers.csproj
  src/GRA.Controllers/MissionControl/ChallengesController.cs
  src/GRA.Controllers/MissionControl/EventsController.cs
  src/GRA.Controllers/MissionControl/ProgramsController.cs
  src/GRA.Controllers/MissionControl/TriggersController.cs
  src/GRA.Domain.Service/BadgeService.cs
  src/GRA.Domain.Service/EventImportService.cs
  src/GRA.Domain.Service/GRA.Domain.Service.csproj
  src/GRA.Web/Areas/MissionControl/Views/Challenges/Create.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Challenges/Edit.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Events/AddEditStreaming.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Events/Create.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Programs/Detail.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Triggers/Detail.cshtml
  src/GRA/ImageType.cs
  src/GRA/SiteSettingDefinitions.cs
  src/GRA/SiteSettingKey.cs
Labels: enhancement, hacktoberfest-accepted

#681 Fix Google Analytics dimensions
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/Views/Shared/_Layout.cshtml
Labels: bug, hacktoberfest-accepted
