Repository MCLD/greatreadingadventure, pull requests merged in 2020-01, with the labels that each got.

#585 Handle goodbye page loads with no valid branch
  src/GRA.Controllers/HomeController.cs
  src/GRA.Web/Views/Home/ExitAccessClosed.cshtml
  src/GRA.Web/Views/Home/ExitAccessClosed.es.cshtml
  src/GRA.Web/Views/Home/ExitBeforeRegistration.cshtml
  src/GRA.Web/Views/Home/ExitBeforeRegistration.es.cshtml
  src/GRA.Web/Views/Home/ExitProgramEnded.cshtml
  src/GRA.Web/Views/Home/ExitProgramEnded.es.cshtml
  src/GRA.Web/Views/Home/ExitProgramOpen.cshtml
  src/GRA.Web/Views/Home/ExitProgramOpen.es.cshtml
  src/GRA.Web/Views/Home/ExitRegistrationOpen.cshtml
  src/GRA.Web/Views/Home/ExitRegistrationOpen.es.cshtml
  src/GRA.Web/Views/Home/IndexAccessClosed.cshtml
  src/GRA.Web/Views/Home/IndexAccessClosed.es.cshtml
  src/GRA.Web/Views/Home/IndexBeforeRegistration.cshtml
  src/GRA.Web/Views/Home/IndexBeforeRegistration.es.cshtml
  src/GRA.Web/Views/Home/IndexProgramEnded.cshtml
  src/GRA.Web/Views/Home/IndexProgramEnded.es.cshtml
  src/GRA.Web/Views/Home/IndexProgramOpen.cshtml
  src/GRA.Web/Views/Home/IndexProgramOpen.es.cshtml
  src/GRA.Web/Views/Home/IndexRegistrationOpen.cshtml
  src/GRA.Web/Views/Home/IndexRegistrationOpen.es.cshtml
Labels: bug

#586 Improve structured logging
  docs/technical/appsettings.md
  src/GRA.Domain.Service/ActivityService.cs
  src/GRA.Domain.Service/AuthenticationService.cs
  src/GRA.Domain.Service/GRA.Domain.Service.csproj
  src/GRA.Domain.Service/JobService.cs
  src/GRA.Domain.Service/ReportService.cs
  src/GRA.Web/LogConfig.cs
  src/GRA.Web/Startup.cs
  src/GRA.Web/WebSocketHandler.cs
  src/GRA.Web/appsettings.json
  src/GRA/ConfigurationKey.cs
  src/GRA/LoggingEnrichment.cs
Labels: developer, enhancement

#587 Improve structured logging
  src/GRA.CommandLine/GRA.CommandLine.csproj
  src/GRA.Controllers/Filter/SiteFilter.cs
  src/GRA.Controllers/GRA.Controllers.csproj
  src/GRA.Controllers/MissionControl/AjaxController.cs
  src/GRA.Controllers/SignInController.cs
  src/GRA.Data.SQLite/GRA.Data.SQLite.csproj
  src/GRA.Data.SqlServer/GRA.Data.SqlServer.csproj
  src/GRA.Data/GRA.Data.csproj
  src/GRA.Domain.Model/GRA.Domain.Model.csproj
  src/GRA.Domain.Report/Abstract/BaseReport.cs
  src/GRA.Domain.Report/BadgeReport.cs
  src/GRA.Domain.Report/BadgeTopScoresReport.cs
  src/GRA.Domain.Report/CommunityExperienceReport.cs
  src/GRA.Domain.Report/CurrentStatusByProgramReport.cs
  src/GRA.Domain.Report/CurrentStatusReport.cs
  src/GRA.Domain.Report/GRA.Domain.Report.csproj
  src/GRA.Domain.Report/GroupVendorCodeReport.cs
  src/GRA.Domain.Report/ParticipantPrizeReport.cs
  src/GRA.Domain.Report/ParticipantProgressReport.cs
  src/GRA.Domain.Report/PrizeRedemptionCountReport.cs
  src/GRA.Domain.Report/PrizeRedemptionReport.cs
  src/GRA.Domain.Report/RegistrationsAchieversBySchoolReport.cs
  src/GRA.Domain.Report/RegistrationsAchieversReport.cs
  src/GRA.Domain.Report/TopScoresReport.cs
  src/GRA.Domain.Report/VendorCodeDonationsReport.cs
  src/GRA.Domain.Report/VendorCodeReport.cs
  src/GRA.Domain.Repository/GRA.Domain.Repository.csproj
  src/GRA.Domain.Service/BadgeService.cs
  src/GRA.Domain.Service/ChallengeService.cs
  src/GRA.Domain.Service/GRA.Domain.Service.csproj
  src/GRA.Security/GRA.Security.csproj
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/LogConfig.cs
  src/GRA.Web/Program.cs
  src/GRA.Web/Startup.cs
  src/GRA.Web/WebSocketHandler.cs
  src/GRA/ConfigurationKey.cs
  src/GRA/GRA.csproj
  src/GRA/LoggingEnrichment.cs
  src/GRA/Version.cs
Labels: developer

#588 Missing events and challenges are 404s
  src/GRA.Controllers/ChallengesController.cs
  src/GRA.Controllers/EventsController.cs
  src/GRA.Domain.Service/ChallengeService.cs
  src/GRA.Domain.Service/EventService.cs
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/Views/Events/Detail.cshtml
  src/GRA.Web/Views/Shared/_Layout.cshtml
Labels: bug, enhancement

#589 Fix and unify Docker build process
  .gitignore
  Dockerfile
  GreatReadingAdventure.sln
  docker-build.bash
  release-prep.bash
  release-publish.bash
Labels: developer, enhancement

#590 Add Seq API Key; remove SiteIdentifier
  src/GRA.Web/LogConfig.cs
  src/GRA.Web/Program.cs
  src/GRA.Web/appsettings.json
  src/GRA/ConfigurationKey.cs
  src/GRA/LoggingEnrichment.cs
Labels: enhancement

#591 Improve logging further
  src/GRA.Controllers/SignInController.cs
  src/GRA.Domain.Service/AuthenticationService.cs
  src/GRA.Web/Areas/MissionControl/Views/Shared/_Layout.cshtml
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/LogConfig.cs
  src/GRA.Web/Program.cs
  src/GRA.Web/Startup.cs
  src/GRA/ConfigurationKey.cs
  src/GRA/LoggingEnrichment.cs
Labels: enhancement

#593 Fix reverse proxy IP logging, session parameters
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/Startup.cs
Labels: bug

#596 Various fixes
  README.md
  docker-build.bash
  src/GRA.Domain.Service/EmailBulkService.cs
  src/GRA.Domain.Service/EmailManagementService.cs
  src/GRA.Domain.Service/EmailService.cs
  src/GRA.Web/GRA.Web.csproj
  src/GRA/Resources/Shared.en.resx
Labels: bug, developer, enhancement

#599 Improve user service logging
  src/GRA.Domain.Service/UserService.cs
Labels: developer, enhancement

#598 Adding Email Management
  src/GRA.Controllers/MissionControl/EmailManagementController.cs
  src/GRA.Controllers/ViewModel/MissionControl/EmailManagement/EmailDetailViewModel.cs
  src/GRA.Controllers/ViewModel/MissionControl/EmailManagement/EmailIndexViewModel.cs
  src/GRA.Data/Model/EmailTemplate.cs
  src/GRA.Data/Repository/EmailTemplateRepository.cs
  src/GRA.Domain.Model/EmailTemplate.cs
  src/GRA.Domain.Model/JobDetailsSendBulkEmails.cs
  src/GRA.Domain.Model/Permission.cs
  src/GRA.Domain.Model/Policy.cs
  src/GRA.Domain.Repository/IEmailTemplateRepository.cs
  src/GRA.Domain.Service/EmailBulkService.cs
  src/GRA.Domain.Service/EmailManagementService.cs
  src/GRA.Domain.Service/EmailService.cs
  src/GRA.Web/Areas/MissionControl/Views/EmailManagement/Detail.cshtml
  src/GRA.Web/Areas/MissionControl/Views/EmailManagement/Index.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Shared/_Layout.cshtml
  src/GRA.Web/GRA.Web.csproj
Labels: enhancement
