Repository MCLD/greatreadingadventure, pull requests merged in 2020-12, with the labels that each got.

#693 Fix issue with adding challenge tasks; environment
  src/GRA.Controllers/Filter/SiteFilter.cs
  src/GRA.Data/Repository/ChallengeTaskRepository.cs
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/Program.cs
  src/GRA/ConfigurationKey.cs
  src/GRA/PathResolver.cs
  src/GRA/ViewTemplates.cs
Labels: bug

#694 Add dotnet outdated GitHub action
  .github/workflows/build-docker-image.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/dotnet-outdated.yml
Labels: dependencies, developer

#680 Add accessibility to carousels
  src/GRA.Web/Views/Home/Dashboard.cshtml
  src/GRA.Web/Views/Home/Dashboard.es.cshtml
Labels: hacktoberfest-accepted

#696 Fix issue with adding carousels
  src/GRA.Controllers/MissionControl/CarouselsController.cs
  src/GRA.Controllers/ViewModel/PageAction.cs
  src/GRA.Web/Areas/MissionControl/Views/Carousels/Index.cshtml
  src/GRA.Web/GRA.Web.csproj
Labels: bug

#697 Update packages
  src/GRA.CommandLine/GRA.CommandLine.csproj
  src/GRA.Controllers/GRA.Controllers.csproj
  src/GRA.Data.SQLite/GRA.Data.SQLite.csproj
  src/GRA.Data.SqlServer/GRA.Data.SqlServer.csproj
  src/GRA.Data/GRA.Data.csproj
  src/GRA.Domain.Model/GRA.Domain.Model.csproj
  src/GRA.Domain.Report/GRA.Domain.Report.csproj
  src/GRA.Domain.Repository/GRA.Domain.Repository.csproj
  src/GRA.Domain.Service/GRA.Domain.Service.csproj
  src/GRA.Security/GRA.Security.csproj
  src/GRA.Web/GRA.Web.csproj
  src/GRA/GRA.csproj
  test/GRA.Test/GRA.Test.csproj
Labels: developer

#698 Update packages for ASP.NET 5.0.1
  src/GRA.CommandLine/GRA.CommandLine.csproj
  src/GRA.Data.SQLite/GRA.Data.SQLite.csproj
  src/GRA.Data.SqlServer/GRA.Data.SqlServer.csproj
  src/GRA.Data/GRA.Data.csproj
  src/GRA.Domain.Report/GRA.Domain.Report.csproj
  src/GRA.Domain.Service/GRA.Domain.Service.csproj
  src/GRA.Security/GRA.Security.csproj
  src/GRA.Web/GRA.Web.csproj
  src/GRA/GRA.csproj
Labels: dependencies

#700 Update dependencies
  .github/workflows/build.yml
  .github/workflows/packages.yml
  src/GRA.CommandLine/GRA.CommandLine.csproj
  src/GRA.Controllers/GRA.Controllers.csproj
Labels: dependencies

#702 Update to new build script
  .github/workflows/build.yml
  .travis.yml
  appveyor.yml
  build.bash
  docker-build.bash
Labels: developer, enhancement

#703 Pass through GHCR_OWNER from secrets
  .github/workflows/build.yml
Labels: bug, developer

#704 Update build script and process
  Dockerfile
  build.bash
Labels: developer

#705 Fix build badge in README
  README.md
Labels: developer
