Repository MCLD/greatreadingadventure, pull requests merged in 2020-03, with the labels that each got.

#612 Return 404 for missing private files
  src/GRA.Controllers/MissionControl/FilesController.cs
Labels: bug

#618 Add vendor code interface documentation
  docs/index.rst
  docs/setup/vendor-codes.md
Labels: documentation

#623 Add vendor code generation job interface
  CHANGELOG.md
  src/GRA.Controllers/MissionControl/FlightController.cs
  src/GRA.Controllers/MissionControl/ParticipantsController.cs
  src/GRA.Domain.Model/JobDetailsGenerateVendorCodes.cs
  src/GRA.Domain.Model/JobType.cs
  src/GRA.Domain.Service/Abstract/BaseService.cs
  src/GRA.Domain.Service/JobService.cs
  src/GRA.Domain.Service/VendorCodeService.cs
  src/GRA.Web/GRA.Web.csproj
Labels: developer, enhancement
