Repository MCLD/greatreadingadventure, pull requests merged in 2021-05, with the labels that each got.

#755 Fix MC household add existing participant
  CHANGELOG.md
  src/GRA.Data/Repository/UserRepository.cs
  src/GRA.Domain.Service/UserService.cs
  src/GRA.Web/GRA.Web.csproj
Labels: bug

#761 Update packages
  src/GRA.Controllers/GRA.Controllers.csproj
  src/GRA.Data.SQLite/GRA.Data.SQLite.csproj
  src/GRA.Data.SqlServer/GRA.Data.SqlServer.csproj
  src/GRA.Data/GRA.Data.csproj
  src/GRA.Domain.Service/GRA.Domain.Service.csproj
  src/GRA.Security/GRA.Security.csproj
  src/GRA.Web/GRA.Web.csproj
  src/GRA/GRA.csproj
Labels: dependencies, developer

#763 Ability to view a list of users assigned each role
  CHANGELOG.md
  global.json
  src/GRA.Controllers/MissionControl/RolesController.cs
  src/GRA.Controllers/ViewModel/MissionControl/Roles/RoleDetailViewModel.cs
  src/GRA.Controllers/ViewModel/MissionControl/Roles/RoleListViewModel.cs
  src/GRA.Controllers/ViewModel/MissionControl/Roles/UsersInRoleViewModel.cs
  src/GRA.Data/Repository/RoleRepository.cs
  src/GRA.Data/Repository/UserRepository.cs
  src/GRA.Domain.Repository/IRoleRepository.cs
  src/GRA.Domain.Repository/IUserRepository.cs
  src/GRA.Domain.Service/RoleService.cs
  src/GRA.Domain.Service/UserService.cs
  src/GRA.Web/Areas/MissionControl/Views/Roles/Detail.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Roles/Index.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Roles/UsersInRole.cshtml
  src/GRA.Web/GRA.Web.csproj
  test/GRA.Test/GRA.Test.csproj
Labels: dependencies, enhancement

#764 Revise Dashboard.es.cshtml to match English one
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/Views/Home/Dashboard.es.cshtml
Labels: bug

#765 Fix participant search
  src/GRA.Data/Repository/UserRepository.cs
  src/GRA.Web/GRA.Web.csproj
Labels: bug

#766 Update package
  src/GRA.Domain.Service/GRA.Domain.Service.csproj
  src/GRA.Web/GRA.Web.csproj
Labels: dependencies
