Repository MCLD/greatreadingadventure, pull requests merged in 2021-12, with the labels that each got.

#813 Update avatar import to fix path bug
  CHANGELOG.md
  src/GRA.Controllers/MissionControl/AvatarsController.cs
  src/GRA.Domain.Model/JobDetailsAvatarImport.cs
  src/GRA.Domain.Service/AvatarService.cs
  src/GRA.Web/GRA.Web.csproj
Labels: bug, developer

#814 Update build script to v1.1.0
  build.bash
Labels: enhancement, developer

#815 Update packages
  src/GRA.CommandLine/GRA.CommandLine.csproj
  src/GRA.Domain.Service/GRA.Domain.Service.csproj
  src/GRA.Web/GRA.Web.csproj
Labels: developer, dependencies

#816 Incorrect Profile tooltip annotations referenced
  CHANGELOG.md
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/Views/Profile/Index.cshtml
Labels: bug

#817 Fix localization issues
  CHANGELOG.md
  src/GRA.Controllers/HomeController.cs
  src/GRA.Web/GRA.Web.csproj
  src/GRA/Resources/Shared.es.resx
Labels: bug

#818 Fix performer registration button
  CHANGELOG.md
  src/GRA.Web/Areas/MissionControl/Views/PerformerManagement/PerformerDetails.cshtml
  src/GRA.Web/Areas/PerformerRegistration/Views/Home/Information.cshtml
  src/GRA.Web/GRA.Web.csproj
Labels: bug

#822 Update packages
  .editorconfig
  src/GRA.Data.SQLite/GRA.Data.SQLite.csproj
  src/GRA.Data.SqlServer/GRA.Data.SqlServer.csproj
  src/GRA.Data/GRA.Data.csproj
  src/GRA.Domain.Service/GRA.Domain.Service.csproj
  src/GRA.Security/GRA.Security.csproj
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/Startup.cs
  src/GRA/GRA.csproj
Labels: developer, dependencies

#824 Fix performer view selections button showing
  CHANGELOG.md
  src/GRA.Web/Areas/MissionControl/Views/PerformerManagement/Performer.cshtml
  src/GRA.Web/GRA.Web.csproj
Labels: bug

#825 Improve streaming program display on dashboard
  CHANGELOG.md
  src/GRA.Controllers/HomeController.cs
  src/GRA.Data/Repository/EventRepository.cs
  src/GRA.Domain.Model/Filters/EventFilter.cs
  src/GRA.Domain.Service/EventService.cs
  src/GRA.Web/GRA.Web.csproj
Labels: enhancement
