Repository MCLD/greatreadingadventure, pull requests merged in 2021-04, with the labels that each got.

#737 Name cookies; fix vendor code documentation
  CHANGELOG.md
  manual/setup/vendor-codes.md
  src/GRA.Domain.Model/VendorCodeType.cs
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/Startup.cs
Labels: bug

#738 Update packages
  src/GRA.Controllers/GRA.Controllers.csproj
  src/GRA.Domain.Report/GRA.Domain.Report.csproj
  src/GRA.Domain.Service/GRA.Domain.Service.csproj
  src/GRA.Web/GRA.Web.csproj
  src/GRA/GRA.csproj
  test/GRA.Test/GRA.Test.csproj
Labels: dependencies

#739 Fix version of curl for health monitoring
  Dockerfile
  src/GRA.Web/GRA.Web.csproj
Labels: dependencies

#740 Fix modal close button
  src/GRA.Web/Areas/MissionControl/Views/Challenges/Create.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Challenges/Edit.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Events/AddEditStreaming.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Events/Create.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Programs/Detail.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Triggers/Detail.cshtml
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/Views/Home/Dashboard.cshtml
  src/GRA.Web/Views/Home/Dashboard.es.cshtml
  src/GRA.Web/Views/Profile/Household.cshtml
Labels: bug

#743 Update packages
  src/GRA.Data.SQLite/GRA.Data.SQLite.csproj
  src/GRA.Data.SqlServer/GRA.Data.SqlServer.csproj
  src/GRA.Data/GRA.Data.csproj
  src/GRA.Domain.Service/GRA.Domain.Service.csproj
  src/GRA.Security/GRA.Security.csproj
  src/GRA.Web/GRA.Web.csproj
  src/GRA/GRA.csproj
Labels: dependencies, developer

#742 Add daily tip upload interface to Mission Control
  src/GRA.Controllers/HomeController.cs
  src/GRA.Controllers/MissionControl/DailyTipsController.cs
  src/GRA.Controllers/MissionControl/ProgramsController.cs
  src/GRA.Controllers/ProfileController.cs
  src/GRA.Controllers/ViewModel/MissionControl/DailyTips/TipListViewModel.cs
  src/GRA.Controllers/ViewModel/MissionControl/DailyTips/TipUploadViewModel.cs
  src/GRA.Data/Repository/DailyLiteracyTipImageRepository.cs
  src/GRA.Domain.Repository/IDailyLiteracyTipImageRepository.cs
  src/GRA.Domain.Service/DailyLiteracyTipService.cs
  src/GRA.Web/Areas/MissionControl/Views/DailyTips/Index.cshtml
  src/GRA.Web/Areas/MissionControl/Views/DailyTips/Upload.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Shared/_Layout.cshtml
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/Views/Home/Dashboard.cshtml
  src/GRA.Web/Views/Home/Dashboard.es.cshtml
Labels: enhancement

#745 Fix Windows CI build
  CHANGELOG.md
  appveyor.yml
  src/GRA.Web/GRA.Web.csproj
Labels: bug, developer

#746 Code improvements
  src/GRA.Data.SqlServer/GlobalSuppressions.cs
  src/GRA.Web/GRA.Web.csproj
  src/GRA/GRA.csproj
Labels: developer

#747 Update CsvHelper package
  src/GRA.Domain.Service/GRA.Domain.Service.csproj
Labels: dependencies, developer

#748 Fix OpenGraph link localization
  src/GRA.Controllers/Helpers/SocialTagHelper.cs
  src/GRA.Controllers/MissionControl/SocialController.cs
  src/GRA.Domain.Service/SocialManagementService.cs
  src/GRA.Web/GRA.Web.csproj
Labels: bug

#751 Fix migration causing upgrade failure from 4.1.1
  src/GRA.Data.SqlServer/Migrations/20190329202403_add-page-i18n.cs
  src/GRA.Web/GRA.Web.csproj
Labels: bug

#752 Update packages
  src/GRA.CommandLine/GRA.CommandLine.csproj
  src/GRA.Domain.Service/GRA.Domain.Service.csproj
  src/GRA.Web/GRA.Web.csproj
Labels: dependencies
