Repository MCLD/greatreadingadventure, pull requests merged in 2021-08, with the labels that each got.

#784 Fix not-allowed cursor on inputs in FireFox
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/Styles/gra.css
  src/GRA.Web/wwwroot/css/main.min.css
  src/GRA.Web/wwwroot/js/main.min.js
  src/GRA.Web/wwwroot/js/markdown.min.js
Labels: bug

#789 Update package
  src/GRA.CommandLine/GRA.CommandLine.csproj
  src/GRA.Web/GRA.Web.csproj
Labels: dependencies

#788 Add date to CreatedBy display in Mission Control
  src/GRA.Web/Areas/MissionControl/Views/Challenges/Edit.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Challenges/Index.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Drawing/Criteria.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Drawing/CriteriaDetail.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Drawing/Detail.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Drawing/Index.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Events/AddEditStreaming.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Events/Edit.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Events/Index.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Triggers/Detail.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Triggers/Index.cshtml
  src/GRA.Web/GRA.Web.csproj
Labels: enhancement
