Repository MCLD/greatreadingadventure, pull requests merged in 2021-06, with the labels that each got.

#767 Fix event spatial proximity searching
  CHANGELOG.md
  src/GRA.Data/Repository/SpatialDistanceRepository.cs
  src/GRA.Web/GRA.Web.csproj
Labels: bug

#769 Remove unused references
  src/GRA.CommandLine/GRA.CommandLine.csproj
  src/GRA.CommandLine/Program.cs
  src/GRA.Controllers/GRA.Controllers.csproj
  src/GRA.Data.SQLite/GRA.Data.SQLite.csproj
  src/GRA.Data.SqlServer/GRA.Data.SqlServer.csproj
  src/GRA.Data/GRA.Data.csproj
  src/GRA.Domain.Model/GRA.Domain.Model.csproj
  src/GRA.Domain.Report/GRA.Domain.Report.csproj
  src/GRA.Domain.Repository/GRA.Domain.Repository.csproj
  src/GRA.Domain.Service/GRA.Domain.Service.csproj
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/Program.cs
  src/GRA/GRA.csproj
Labels: dependencies, developer

#770 Add TreatAsUsed tags, explicit reference
  src/GRA.Data.SQLite/GRA.Data.SQLite.csproj
  src/GRA.Data.SqlServer/GRA.Data.SqlServer.csproj
  src/GRA.Web/GRA.Web.csproj
Labels: dependencies

#771 Fix error on goodbye page
  src/GRA.Controllers/HomeController.cs
  src/GRA.Web/GRA.Web.csproj
Labels: bug

#772 Fix remove button logic on avatar page
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/Views/Avatar/Index.cshtml
Labels: bug

#773 Update packages
  src/GRA.Data.SQLite/GRA.Data.SQLite.csproj
  src/GRA.Data.SqlServer/GRA.Data.SqlServer.csproj
  src/GRA.Data/GRA.Data.csproj
  src/GRA.Security/GRA.Security.csproj
  src/GRA.Web/GRA.Web.csproj
  src/GRA/GRA.csproj
Labels: dependencies

#776 Update MailKit and MimeKit packages
  src/GRA.Domain.Service/GRA.Domain.Service.csproj
  src/GRA.Web/GRA.Web.csproj
Labels: dependencies

#760 Disable Book List's "Add Book" button before program starts
  CHANGELOG.md
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/Views/Profile/Books.cshtml
  src/GRA/Annotations.cs
  src/GRA/Resources/Shared.en.resx
  src/GRA/Resources/Shared.es.resx
Labels: awaiting translation
