Repository MCLD/greatreadingadventure, pull requests merged in 2021-09, with the labels that each got.

#790 Add site setting to show participants library in footer
  .dockerignore
  src/GRA.Controllers/Filter/UserFilter.cs
  src/GRA.Controllers/Helpers/InfoLinksTagHelper.cs
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/Styles/gra.css
  src/GRA.Web/wwwroot/css/main.min.css
  src/GRA/Annotations.cs
  src/GRA/Resources/Shared.en.resx
  src/GRA/Resources/Shared.es.resx
  src/GRA/SiteSettingDefinitions.cs
  src/GRA/SiteSettingKey.cs
Labels: enhancement, awaiting translation

#791 Add "back to family" to MC prize view
  src/GRA.Web/Areas/MissionControl/Views/Participants/Prizes.cshtml
  src/GRA.Web/GRA.Web.csproj
Labels: enhancement

#793 Fix minor translation issues
  src/GRA/Resources/Shared.en.resx
  src/GRA/Resources/Shared.es.resx
Labels: i18n

#794 Update changelog; outdated packages
  CHANGELOG.md
  src/GRA.Data.SQLite/GRA.Data.SQLite.csproj
  src/GRA.Data.SqlServer/GRA.Data.SqlServer.csproj
  src/GRA.Data/GRA.Data.csproj
  src/GRA.Domain.Service/GRA.Domain.Service.csproj
  src/GRA.Security/GRA.Security.csproj
  src/GRA.Web/GRA.Web.csproj
  src/GRA/GRA.csproj
Labels: developer, documentation, dependencies

#795 Display list of participating libraries
  src/GRA.Controllers/Helpers/InfoLinksTagHelper.cs
  src/GRA.Controllers/InfoController.cs
  src/GRA.Controllers/ParticipatingLibrariesController.cs
  src/GRA.Controllers/ViewModel/ParticipatingLibraries/ParticipatingLibrariesViewModel.cs
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/Styles/gra.css
  src/GRA.Web/Views/ParticipatingLibraries/Index.cshtml
  src/GRA.Web/wwwroot/css/main.min.css
  src/GRA/Annotations.cs
  src/GRA/Resources/Shared.en.resx
  src/GRA/Resources/Shared.es.resx
  src/GRA/SiteSettingDefinitions.cs
  src/GRA/SiteSettingKey.cs
Labels: enhancement, awaiting translation
