Repository MCLD/greatreadingadventure, pull requests merged in 2022-03, with the labels that each got.

#844 Show the wrench icon to all Mission Control users
  CHANGELOG.md
  Dockerfile
  src/GRA.Data.SQLite/GRA.Data.SQLite.csproj
  src/GRA.Data.SqlServer/GRA.Data.SqlServer.csproj
  src/GRA.Data/GRA.Data.csproj
  src/GRA.Security/GRA.Security.csproj
  src/GRA.Web/Areas/MissionControl/Views/Shared/_Layout.cshtml
  src/GRA.Web/GRA.Web.csproj
  src/GRA/GRA.csproj
Labels: enhancement

#839 Add vendor prize improvements
  CHANGELOG.md
  manual/setup/vendor-codes.md
  src/GRA.CommandLine/GRA.CommandLine.csproj
  src/GRA.Controllers/GRA.Controllers.csproj
  src/GRA.Controllers/HomeController.cs
  src/GRA.Controllers/MissionControl/VendorCodesController.cs
  src/GRA.Controllers/ViewModel/Home/DashboardViewModel.cs
  src/GRA.Data/Model/VendorCode.cs
  src/GRA.Data/Repository/PrizeWinnerRepository.cs
  src/GRA.Domain.Model/JobDetailsReceivePackingSlip.cs
  src/GRA.Domain.Model/PackingSlipSummary.cs
  src/GRA.Domain.Model/User.cs
  src/GRA.Domain.Model/VendorCode.cs
  src/GRA.Domain.Model/VendorOrderStatus.cs
  src/GRA.Domain.Repository/IPrizeWinnerRepository.cs
  src/GRA.Domain.Service/GRA.Domain.Service.csproj
  src/GRA.Domain.Service/PrizeWinnerService.cs
  src/GRA.Domain.Service/VendorCodeService.cs
  src/GRA.Web/Areas/MissionControl/Views/Participants/Detail.cshtml
  src/GRA.Web/Areas/MissionControl/Views/VendorCodes/ViewPackingSlip.cshtml
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/Styles/gra.css
  src/GRA.Web/Views/Home/Dashboard.cshtml
  src/GRA.Web/Views/Home/Dashboard.es.cshtml
  src/GRA.Web/Views/Profile/Index.cshtml
  src/GRA.Web/wwwroot/css/main.min.css
  src/GRA/Annotations.cs
  src/GRA/Resources/Shared.en.resx
  src/GRA/Resources/Shared.es.resx
  test/GRA.Test/VerifyResourcesTest.cs
Labels: enhancement, awaiting translation, migration needed

#847 Add sign in again button to exit pages
  CHANGELOG.md
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/Views/Home/ExitProgramEnded.cshtml
  src/GRA.Web/Views/Home/ExitProgramEnded.es.cshtml
  src/GRA.Web/Views/Home/ExitProgramOpen.cshtml
  src/GRA.Web/Views/Home/ExitProgramOpen.es.cshtml
  src/GRA/Annotations.cs
  src/GRA/Resources/Shared.en.resx
  src/GRA/Resources/Shared.es.resx
Labels: enhancement

#849 Fix error in MC with deleted news posting user
  CHANGELOG.md
  src/GRA.Data/Repository/UserRepository.cs
  src/GRA.Domain.Repository/IUserRepository.cs
  src/GRA.Domain.Service/UserService.cs
  src/GRA.Web/GRA.Web.csproj
Labels: bug
