Repository MCLD/greatreadingadventure, pull requests merged in 2023-11, with the labels that each got.

#1049 Update package; update Docker lock checksums
  docker-lock.json
  src/GRA.Web/GRA.Web.csproj
  test/GRA.Test/GRA.Test.csproj
Labels: dependencies

#1048 Redirect performer to dashboard prior to program start
  CHANGELOG.md
  src/GRA.Controllers/PerformerRegistration/HomeController.cs
  src/GRA.Controllers/SignInController.cs
Labels: enhancement

#1055 Update xunit package
  test/GRA.Test/GRA.Test.csproj
Labels: dependencies

#1054 Add configurable back to back performance options
  CHANGELOG.md
  src/GRA.Controllers/MissionControl/SitesController.cs
  src/GRA.Controllers/PerformerRegistration/HomeController.cs
  src/GRA.Controllers/ViewModel/PerformerRegistration/Home/ProgramViewModel.cs
  src/GRA.Domain.Model/SiteSettingFormat.cs
  src/GRA.Web/Areas/MissionControl/Views/Sites/Settings.cshtml
  src/GRA.Web/Areas/PerformerRegistration/Views/Home/Program.cshtml
  src/GRA.Web/GRA.Web.csproj
  src/GRA/Defaults.cs
  src/GRA/SiteSettingDefinitions.cs
  src/GRA/SiteSettingKey.cs
Labels: enhancement

#1057 Update Microsoft.NET.Test.Sdk package
  test/GRA.Test/GRA.Test.csproj
Labels: dependencies

#1059 Update Serilog 3.0.1 -> 3.1.0
  src/GRA.Controllers/GRA.Controllers.csproj
  src/GRA.Domain.Service/GRA.Domain.Service.csproj
  src/GRA/GRA.csproj
Labels: dependencies

#1058 Add back to back dropdown to mc performer management
  src/GRA.Controllers/MissionControl/PerformerManagementController.cs
  src/GRA.Controllers/ViewModel/MissionControl/PerformerManagement/ProgramDetailsViewModel.cs
  src/GRA.Web/Areas/MissionControl/Views/PerformerManagement/ProgramDetails.cshtml
Labels: bug, enhancement

#1060 Update change log; bump revision number
  CHANGELOG.md
  src/GRA.Web/GRA.Web.csproj
Labels: developer

#1062 Update packages: Mailkit, Mimekit, Serilog
  src/GRA.Controllers/GRA.Controllers.csproj
  src/GRA.Domain.Service/GRA.Domain.Service.csproj
  src/GRA.Web/GRA.Web.csproj
  src/GRA/GRA.csproj
Labels: dependencies

#1063 Change verbage to Community Reading Goal
  CHANGELOG.md
  src/GRA.Web/GRA.Web.csproj
  src/GRA/Annotations.cs
  src/GRA/Resources/Shared.en.resx
  src/GRA/Resources/Shared.es.resx
Labels: enhancement

#1061 Update dashboard and streaming page with date
  CHANGELOG.md
  Dockerfile
  docker-lock.json
  src/GRA.Controllers/EventsController.cs
  src/GRA.Controllers/ViewModel/Events/StreamViewModel.cs
  src/GRA.Data.SQLite/GRA.Data.SQLite.csproj
  src/GRA.Data.SqlServer/GRA.Data.SqlServer.csproj
  src/GRA.Data/GRA.Data.csproj
  src/GRA.Security/GRA.Security.csproj
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/Views/Events/Stream.cshtml
  src/GRA.Web/Views/Home/Dashboard.cshtml
  src/GRA.Web/Views/Home/Dashboard.es.cshtml
  src/GRA/Annotations.cs
  src/GRA/GRA.csproj
  src/GRA/Resources/Shared.en.resx
  src/GRA/Resources/Shared.es.resx
Labels: enhancement, awaiting translation

#1067 Add job system and welcome emails
  .editorconfig
  CHANGELOG.md
  manual/index.rst
  manual/setup/email.md
  manual/technical/appsettings.md
  src/GRA.Controllers/Base/MCController.cs
  src/GRA.Controllers/MissionControl/EmailManagementController.cs
  src/GRA.Controllers/MissionControl/HomeController.cs
  src/GRA.Controllers/ViewModel/MissionControl/EmailManagement/EmailIndexViewModel.cs
  src/GRA.Data/Repository/UserRepository.cs
  src/GRA.Domain.Repository/IUserRepository.cs
  src/GRA.Domain.Service/EmailBulkService.cs
  src/GRA.Domain.Service/SiteLookupService.cs
  src/GRA.Domain.Service/SiteService.cs
  src/GRA.Domain.Service/UserService.cs
  src/GRA.Web/Areas/MissionControl/Views/EmailManagement/Index.cshtml
  src/GRA.Web/Areas/MissionControl/Views/EmailManagement/SpecialEmails.cshtml
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/JobBackgroundService.cs
  src/GRA.Web/JobTaskRunner.cs
  src/GRA.Web/Startup.cs
  src/GRA/CacheKey.cs
  src/GRA/ConfigurationKey.cs
  src/GRA/SiteSettingDefinitions.cs
  src/GRA/SiteSettingKey.cs
Labels: enhancement
