Repository MCLD/greatreadingadventure, pull requests merged in 2023-12, with the labels that each got.

#1072 Update packages
  docker-lock.json
  src/GRA.Controllers/GRA.Controllers.csproj
  src/GRA.Domain.Service/GRA.Domain.Service.csproj
  src/GRA.Web/GRA.Web.csproj
  test/GRA.Test/GRA.Test.csproj
Labels: dependencies

#1068 Change program to age group where shown to participants
  src/GRA.Domain.Model/Metadata/DisplayNames.cs
  src/GRA/Annotations.cs
  src/GRA/Resources/Shared.en.resx
  src/GRA/Resources/Shared.es.resx
Labels: awaiting translation

#1074 Fix changelog and version
  CHANGELOG.md
  src/GRA.Web/GRA.Web.csproj
Labels: enhancement

#1069 Add performer coversheet generation
  CHANGELOG.md
  src/GRA.Controllers/MissionControl/PerformerManagementController.cs
  src/GRA.Controllers/ViewModel/MissionControl/PerformerManagement/PerformerCoversheetViewModel.cs
  src/GRA.Domain.Service/PerformerSchedulingService.cs
  src/GRA.Web/Areas/MissionControl/Views/PerformerManagement/Performer.cshtml
  src/GRA.Web/Areas/MissionControl/Views/PerformerManagement/Performers.cshtml
  src/GRA.Web/Areas/MissionControl/Views/PerformerManagement/PrepCoverSheet.cshtml
  src/GRA.Web/Areas/MissionControl/Views/PerformerManagement/PrintCoverSheet.cshtml
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/Startup.cs
  src/GRA.Web/Styles/performercoversheet.css
Labels: enhancement

#1076 Fix email compare to be case-insensitive
  src/GRA.Data/Repository/DirectEmailHistoryRepository.cs
  src/GRA.Domain.Repository/IDirectEmailHistoryRepository.cs
  src/GRA.Web/GRA.Web.csproj
Labels: bug

#1077 Fix email case-sensitivity check
  src/GRA.Data/Repository/DirectEmailHistoryRepository.cs
  src/GRA.Domain.Repository/IDirectEmailHistoryRepository.cs
  src/GRA.Domain.Service/EmailBulkService.cs
  src/GRA.Web/GRA.Web.csproj
Labels: bug

#1075 Fix typo in default footer
  src/GRA.Web/assets/defaultitems/DirectEmailTemplateText/EmailTemplateText_Mission-Control-news-post_en-US.json
Labels: bug

#1078 Update packages; Docker lock checksums
  docker-lock.json
  src/GRA.Controllers/GRA.Controllers.csproj
  src/GRA.Domain.Service/GRA.Domain.Service.csproj
  src/GRA.Web/GRA.Web.csproj
  test/GRA.Test/GRA.Test.csproj
Labels: dependencies
