Repository MCLD/greatreadingadventure, pull requests merged in 2023-10, with the labels that each got.

#1041 Update packages
  docker-lock.json
  src/GRA.Controllers/GRA.Controllers.csproj
  src/GRA.Data.SQLite/GRA.Data.SQLite.csproj
  src/GRA.Data.SqlServer/GRA.Data.SqlServer.csproj
  src/GRA.Data/GRA.Data.csproj
  src/GRA.Domain.Service/GRA.Domain.Service.csproj
  src/GRA.Security/GRA.Security.csproj
  src/GRA.Web/GRA.Web.csproj
  src/GRA/GRA.csproj
  test/GRA.Test/GRA.Test.csproj
Labels: dependencies

#1042 Fix pinned curl in Dockerfile
  Dockerfile
Labels: dependencies

#1044 Update packages for .NET 7.0.13
  docker-lock.json
  src/GRA.Data.SQLite/GRA.Data.SQLite.csproj
  src/GRA.Data.SqlServer/GRA.Data.SqlServer.csproj
  src/GRA.Data/GRA.Data.csproj
  src/GRA.Security/GRA.Security.csproj
  src/GRA.Web/GRA.Web.csproj
  src/GRA/GRA.csproj
  test/GRA.Test/GRA.Test.csproj
Labels: developer, dependencies

#1040 Replace calls to deprecated GetBaseUrl
  CHANGELOG.md
  src/GRA.Controllers/AvatarController.cs
  src/GRA.Controllers/MissionControl/AjaxController.cs
  src/GRA.Controllers/MissionControl/ChallengesController.cs
  src/GRA.Controllers/MissionControl/EventsController.cs
  src/GRA.Controllers/MissionControl/PagesController.cs
  src/GRA.Controllers/MissionControl/ProgramsController.cs
  src/GRA.Controllers/ShareController.cs
  src/GRA.Domain.Service/SiteService.cs
  src/GRA.Web/GRA.Web.csproj
Labels: developer

#1045 Add configuration for Read the Docs and fix manual
  .readthedocs.yaml
  manual/_static/great-reading-adventure-logo@1x.png
  manual/conf.py
  manual/index.rst
  manual/installation/configuration.md
  manual/installation/create-the-database.md
  manual/installation/upgrading.md
  manual/requirements.txt
  manual/technical/about.md
Labels: documentation

#1047 Fix typos in introduction overview.md
  manual/introduction/overview.md
Labels: documentation
