Repository MCLD/greatreadingadventure, pull requests merged in 2023-02, with the labels that each got.

#975 Add Roles and Permissions to the manual
  manual/index.rst
  manual/setup/roles-and-permissions.md
Labels: documentation

#976 Update Docker lock checksums
  docker-lock.json
Labels: developer, dependencies

#977 Update Docker lock checksums
  docker-lock.json
Labels: developer, dependencies

#979 Add scheduling improvements
  CHANGELOG.md
  src/GRA.Controllers/MissionControl/PerformerSchedulingController.cs
  src/GRA.Controllers/ViewModel/MissionControl/PerformerScheduling/PerformerViewModel.cs
  src/GRA.Web/Areas/MissionControl/Views/PerformerManagement/Index.cshtml
  src/GRA.Web/Areas/MissionControl/Views/PerformerScheduling/Index.cshtml
  src/GRA.Web/Areas/MissionControl/Views/PerformerScheduling/Performer.cshtml
  src/GRA.Web/GRA.Web.csproj
Labels: enhancement

#973 Add site-wide minute goal with display
  CHANGELOG.md
  src/GRA.Controllers/HomeController.cs
  src/GRA.Controllers/ViewModel/Home/DashboardViewModel.cs
  src/GRA.Data/Repository/UserLogRepository.cs
  src/GRA.Domain.Repository/IUserLogRepository.cs
  src/GRA.Domain.Service/ActivityService.cs
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/Views/Home/Dashboard.cshtml
  src/GRA.Web/Views/Home/Dashboard.es.cshtml
  src/GRA.Web/Views/Home/IndexBeforeRegistration.es.cshtml
  src/GRA/Annotations.cs
  src/GRA/CacheKey.cs
  src/GRA/Resources/Shared.en.resx
  src/GRA/Resources/Shared.es.resx
  src/GRA/SiteSettingDefinitions.cs
  src/GRA/SiteSettingKey.cs
  test/GRA.Test/GRA.Test.csproj
Labels: enhancement
