Repository MCLD/greatreadingadventure, pull requests merged in 2023-05, with the labels that each got.

#1010 Fix 'login as' from participant profile
  CHANGELOG.md
  src/GRA.Controllers/ProfileController.cs
  src/GRA.Web/GRA.Web.csproj
Labels: bug

#1011 Fix MC link from events to challenges; tag helper
  CHANGELOG.md
  docker-lock.json
  src/GRA.Web/Areas/MissionControl/Views/Events/AddEditStreaming.cshtml
  src/GRA.Web/Areas/MissionControl/Views/Events/Edit.cshtml
  src/GRA.Web/Areas/MissionControl/Views/_ViewImports.cshtml
  src/GRA.Web/Areas/PerformerRegistration/Views/_ViewImports.cshtml
  src/GRA.Web/GRA.Web.csproj
Labels: bug

#1012 Update ImageSharp
  src/GRA.Controllers/GRA.Controllers.csproj
  src/GRA.Domain.Service/BadgeService.cs
  src/GRA.Domain.Service/GRA.Domain.Service.csproj
  src/GRA.Web/GRA.Web.csproj
Labels: dependencies

#1013 Update Docker lock checksums
  docker-lock.json
Labels: developer, dependencies

#1009 Whitespace bug on subject and preview input
  src/GRA.Controllers/MissionControl/EmailManagementController.cs
  src/GRA.Controllers/ViewModel/MissionControl/EmailManagement/DetailsViewModel.cs
  src/GRA.Web/Areas/MissionControl/Views/EmailManagement/Details.cshtml
  src/GRA.Web/GRA.Web.csproj
Labels: bug
