Repository MCLD/greatreadingadventure, pull requests merged in 2024-02, with the labels that each got.

#1089 Update packages; Docker lock checksums
  docker-lock.json
  src/GRA.Domain.Service/GRA.Domain.Service.csproj
  src/GRA.Web/GRA.Web.csproj
  test/GRA.Test/GRA.Test.csproj
Labels: dependencies

#1090 Add program and group to hold slips
  CHANGELOG.md
  src/GRA.Controllers/MissionControl/ReportingController.cs
  src/GRA.Controllers/MissionControl/VendorCodesController.cs
  src/GRA.Data/Repository/VendorCodeRepository.cs
  src/GRA.Domain.Model/VendorCode.cs
  src/GRA.Domain.Report/ParticipantProgressReport.cs
  src/GRA.Web/Areas/MissionControl/Views/VendorCodes/HoldSlips.cshtml
  src/GRA.Web/GRA.Web.csproj
Labels: enhancement

#1091 Hold slip generation w/out receiving packing slip
  CHANGELOG.md
  src/GRA.Web/Areas/MissionControl/Views/VendorCodes/ViewPackingSlip.cshtml
  src/GRA.Web/GRA.Web.csproj
Labels: enhancement

#1092 Fix CSS include for performer coversheet report
  src/GRA.Web/GRA.Web.csproj
Labels: bug

#1093 Update packages and Docker lock checksums
  docker-lock.json
  src/GRA.Data.SQLite/GRA.Data.SQLite.csproj
  src/GRA.Data.SqlServer/GRA.Data.SqlServer.csproj
  src/GRA.Data/GRA.Data.csproj
  src/GRA.Domain.Service/GRA.Domain.Service.csproj
  src/GRA.Security/GRA.Security.csproj
  src/GRA.Web/GRA.Web.csproj
  src/GRA/GRA.csproj
Labels: dependencies

#1094 Add perfomer Excel export; upgrade OpenXml
  CHANGELOG.md
  docker-lock.json
  src/GRA.Controllers/GRA.Controllers.csproj
  src/GRA.Controllers/MissionControl/PerformerManagementController.cs
  src/GRA.Controllers/MissionControl/ReportingController.cs
  src/GRA.Controllers/MissionControl/VendorCodesController.cs
  src/GRA.Controllers/ViewModel/MissionControl/EmailManagement/BaseDetailsViewModel.cs
  src/GRA.Web/Areas/MissionControl/Views/PerformerManagement/Index.cshtml
  src/GRA.Web/Areas/MissionControl/Views/PerformerManagement/_PerformerManagementPartial.cshtml
  src/GRA.Web/GRA.Web.csproj
  src/GRA/GRA.csproj
  src/GRA/Utility/ExcelExport.cs
Labels: enhancement
