Repository MCLD/greatreadingadventure, pull requests merged in 2024-01, with the labels that each got.

#1081 Update packages; remove generated-code warnings
  docker-lock.json
  src/GRA.Controllers/GRA.Controllers.csproj
  src/GRA.Data.SQLite/GRA.Data.SQLite.csproj
  src/GRA.Data.SqlServer/GRA.Data.SqlServer.csproj
  src/GRA.Data.SqlServer/GlobalSuppressions.cs
  src/GRA.Data.SqlServer/Properties/AssemblyInfo.cs
  src/GRA.Data/GRA.Data.csproj
  src/GRA.Domain.Service/GRA.Domain.Service.csproj
  src/GRA.Security/GRA.Security.csproj
  src/GRA.Web/GRA.Web.csproj
  src/GRA/GRA.csproj
  test/GRA.Test/GRA.Test.csproj
Labels: dependencies

#1066 Store challenge filters in cookie
  CHANGELOG.md
  docker-lock.json
  src/GRA.Controllers/ChallengesController.cs
  src/GRA.Controllers/ViewModel/Challenges/ChallengesListViewModel.cs
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/Views/Challenges/Index.cshtml
  src/GRA/Annotations.cs
  src/GRA/Defaults.cs
  src/GRA/Resources/Shared.en.resx
  src/GRA/Resources/Shared.es.resx
Labels: enhancement, awaiting translation

#1080 Add site setting to ask new user to add family member
  CHANGELOG.md
  src/GRA.Controllers/Filter/SiteFilter.cs
  src/GRA.Controllers/ItemKey.cs
  src/GRA.Controllers/ViewComponents/DisplayNotificationsViewComponent.cs
  src/GRA.Domain.Model/Notification.cs
  src/GRA.Domain.Service/UserService.cs
  src/GRA.Web/GRA.Web.csproj
  src/GRA.Web/Views/Shared/Components/DisplayNotifications/Alert.cshtml
  src/GRA.Web/Views/Shared/Components/DisplayNotifications/Modal.cshtml
  src/GRA/Annotations.cs
  src/GRA/Resources/Shared.en.resx
  src/GRA/Resources/Shared.es.resx
  src/GRA/SiteSettingDefinitions.cs
  src/GRA/SiteSettingKey.cs
  test/GRA.Test/GRA.Test.csproj
Labels: enhancement, awaiting translation

#1083 Fix pinned version of curl in Dockerfile
  Dockerfile
Labels: developer, dependencies

#1084 Update ef tool version in Dockerfile
  Dockerfile
Labels: developer, dependencies

#1086 Remove migration but keep context update
  src/GRA.Data.SqlServer/Migrations/20240116222853_add-scheduling-point-of-contact.Designer.cs
  src/GRA.Data.SqlServer/Migrations/20240116222853_add-scheduling-point-of-contact.cs
Labels: bug, developer
